### ISSUE TITLE
Account integration

### ISSUE THREAD

**Issue by train860** [turms-im/turms#1004]
I have read the document and js client code, found that login can only use username and password. When integration with business system, the password will be exposed in the client. Is it possible to login through token? And, token can get by server client fetch from turms server, using username and password.

**Comment by JamesChenX** [comment]
I have considered the case, so turms has a plugin system, and you can implement the plugin `im.turms.gateway.infra.plugin.extension.UserAuthenticator` to use your own authentication logic and you can treat `password` as `token` if you want.
Though you can change the source code of Turms, it's not recommended because you need to fork and maintain your own Turms version).

For plugin details, read: https://turms-im.github.io/docs/for-developers/plugin.html

**Comment by train860** [comment]
Got it, thanks
