### ISSUE TITLE
admin api sdk

### ISSUE THREAD

**Issue by itmagus** [turms-im/turms#1012]
请问下，是否有考虑把admin api client单独拿出来做个SDK呢？内外部都可以使用？
还是说要基于
https://github.com/turms-im/proto 
去生成，自己封装哈

**Comment by JamesChenX** [comment]
1. Admin API is HTTP API indeed, e.g. `/users`, and you can just call it using an HTTP client. Or do you want us to provide an admin HTTP API client (For example, written in Java) to call the admin API of turms servers?
If so, it can be an enhancement, but I don't think it's worthwhile to do it honestly because there are so many programming languages and every language can implement HTTP clients in different solutions.

2. For client/server communication that using the models as you have mentioned `https://github.com/turms-im/proto`, we have provided different client SDKs (`turms-client-js/dart/java/swift`), so I think you don't mean the SDKs?
Or do you want to send client requests to admin HTTP API? If not, what scenarios that you need to use client requests? I may provide a more suitable solution for your scenarios.

**Comment by itmagus** [comment]
好的，谢谢，我目前要用的是第一种情况，我提到proto，意思是可以采用相同的方式，生成admin-api的SDK?
(因为有太多的编程语言，每种语言都可以在不同的解决方案中实现 HTTP 客户端) ,说的第二点，应该面对的问题是一样的，js,dart等，也有不同的websocket库和实现方式，模型和接口通过proto应该是可以通用的？

**Comment by itmagus** [comment]
好的，谢谢。
1.我目前要用的是第一种情况，我提到proto，意思是可以采用相同的方式，生成admin-api的SDK的?
我开始认为，下面这一块如果，如果是管理API的CLIENT的话，可以提取出来做为admin-client-sdk的一部分，
![image](https://user-images.githubusercontent.com/8073980/190945510-eaea978c-7235-4b24-ba3f-0e54993e9093.png)
在这个基础上，加上HTTP的调用方式，应该就是一个完整的admin-clent-sdk。
这样的话，我面其他的JAVA的服务里，也可以直接使用，或者只需要自定义HTTP的调用方式。
2. turms-admin,我还没去看不知道是不是通过proto，生成JS的client 加上js的 http调用方式实现的？
3. (因为有太多的编程语言，每种语言都可以在不同的解决方案中实现 HTTP 客户端) ,说的第二点，个人认为，给客户端用的SDK（turms-client-kotlin/js/swift/dart)和给服务端用的SDK(
dmin-client-sdk，对应的是
https://turms-im.github.io/docs/for-developers/admin-api.html
)可以分开，应用场景不一样，实现应该是一样的

**Comment by itmagus** [comment]
当然，目前这样，也很灵活，可以继续走之前的Controller层使用HTTP，也可以从目前DDD的结构中，直接在内部暴露SERVICE层,使用GRPC,ROSCKET，dubbo之类的方式，根据自己的应用体系去改造，问题也不大。
一些微服务的体系里，在内部，本身就存在，不同的语言，之间相互通信的情况，一般也早就有了解决方案，所以在这一块，也确实没必要深入，提供一个HTTP的方式就好了。

**Comment by JamesChenX** [comment]
As you said, HTTP is easy to use enough, so it's not worthwhile to take a lot of effort to provide admin client SDKs currently. And if the admin requests in your scenarios aren't too many, HTTP should be good enough, and it's better to keep things simple to not introduce gRPC/RSocket/Dubble/etc.

btw, although [Swagger Codegen](https://swagger.io/tools/swagger-codegen) can generate client SDK of different languages automatically according to the OpenAPI docs, the generated code is just ugly and terrible to use, so it's not recommended.

**Comment by itmagus** [comment]
嗯，好的
