### ISSUE TITLE
client login

### ISSUE THREAD

**Issue by itmagus** [turms-im/turms#1013]
关于客户端登录，应该怎么正确的理解呢？
 await client.userService.login(Int64(1), password: '123');
一般应用都有自己的认证体系，客户端通过自己的认证就OK了，通过IM管理端API，换取IM认证需要的TOKEN或SESSION之类的认证凭证，给客户端？应该不再需要，再通过IM去做一次认证了？
认证的方式本身就很多种，不一定是需要输入密码的哈，感觉turms不需要管认证的方式和过程，只管鉴权就好了

**Comment by JamesChenX** [comment]
* Use `turms.gateway.session.enable-authentication=false` to disable authentication.
* Or implement `im.turms.gateway.infra.plugin.extension.UserAuthenticator` to use your own authentication logic.

**Comment by itmagus** [comment]
嗯，那应该只能实现UserAuthenticator的逻辑，把认证的凭证放在password中传过去？

**Comment by JamesChenX** [comment]
Yes. And I think the authentication workflow that you want may be similar to OAuth 2.0, and you can take the diagram as an example:
![image](https://user-images.githubusercontent.com/44962329/191042756-39c65478-ab7f-49ea-9c6c-0e36081ed4af.png)

btw, I will provide a PR to support built-in Java plugins so that you don't need to create new projects for plugins, but just create some Java plugin class files in the source code of turms to make your plugin development easier.

**Comment by itmagus** [comment]
嗯，这个图非常正确，
实现这个图的方式有两种方式
其实有两种方式
第一种是OAuth Server用我们自己的，要做插件通过UserAuthenticator去验证。
第二种OAuth Server本来就是turms自己，只是通过管理端的API去获取了access token,这样就不去要去实现UserAuthenticator，去验证access token，turms自己验就行了。
第二种方式的基础上，也可以扩展第一种方式，使用自己的OAuth Server及验证流程

**Comment by JamesChenX** [comment]
I think OAuth is over-engineering for these scenarios currently, which makes things complicated for both turms servers and turms' users like you (because they need to provide an OAuth server).
The workflow of OAuth above is just an example. I can provide two built-in solutions to get authentication from third parties in this month:

The first solution:
1. Client sends a login request to turms server
2. Turms server relays the user's information to your server using HTTP
3. Your server checks the user's authentication according to the HTTP request and sends the result back to Turms server using an HTTP response.

The second way:
1. Client sends a login request to your server
2. Your server returns JWT to the client
3. The client sends the JWT as `password` to turms-gateway so that turms-gateway can decode it and know whether the user is authenticated

**Comment by JamesChenX** [comment]
> 顺便提下，如果在_turmsClient.driver.connect()之前就拿到了access token，这样，连接认证，是否可以一并做了？

No, `connect` is just trying to establish a TCP connection.

**Comment by itmagus** [comment]
> 我认为 OAuth 目前对这些场景进行了过度设计，因为这像他们的团队和用户的事情是（需要提供 OAuth 服务器）。
嗯，这个问题和OAuth本身并无关系，而是turms本身，是否支持：
1.通过admin api从服务端直接获取认证凭证,这个凭证，是JWT还是什么都可以。(如果支持自定义凭证，那就从我自己的服务端获取认证凭证)。
2.获取到的凭证，可以直接应用到client 的login 流程。
3.同意作者的观点，用最简单的方式，实现认证流程的扩展，保持turms的小，和强大的扩展性就好了

**Comment by itmagus** [comment]
我认为 OAuth 目前对这些场景进行了过度设计，因为这像他们的团队和用户的事情是（需要提供 OAuth 服务器）。
嗯，这个问题和OAuth本身并无关系，而是turms本身，是否支持：
1.通过admin api从服务端直接获取认证凭证,这个凭证，是JWT还是什么都可以。(如果支持自定义凭证，那就从我自己的服务端获取认证凭证)。
2.获取到的凭证，可以直接应用到client 的login 流程。
3.同意作者的观点，用最简单的方式，实现认证流程的扩展，保持turms的小，和强大的扩展性就好了

**Comment by JamesChenX** [comment]
It has nothing to do with admin HTTP API. I will write a doc once I implement these two authentication solutions mentioned above this month so that you can reference it.

**Comment by itmagus** [comment]
好的，感谢

**Comment by itmagus** [comment]
@JamesChenX 辛苦了哈，还会给出文档链接不？

**Comment by JamesChenX** [comment]
@itmagus Yes, and I will publish the doc today.

**Comment by JamesChenX** [comment]
@itmagus I have published the doc, and you can check it: https://turms-im.github.io/docs/for-developers/client-identity-access-management.html
