### ISSUE TITLE
user id type

### ISSUE THREAD

**Issue by itmagus** [turms-im/turms#1015]
请问下，应用系统与turms关联，是用user id吗？
现在id是long的类型的，改成string的，兼容性是不是更强一些呢
像如果使用keycloak，直接给的就是个string的ID，string里还可以放其它类型的数据，反之不然
或者新增一个用于关联的字段，应该也可以解决这个问题

**Comment by JamesChenX** [comment]
Use `long` (Int64) instead of `string` because (just my random thoughts):
1. `long` is more efficient (8 bytes) than string when persisting them in DB. Note that a lot of turms' collections in MongoDB need to save user IDs.
2. `long` (varint) is more efficient (1~9 bytes) when transferring in the network.
3. Easy to generate a global random ID using the snowflake ID generator.
4. The range of `long` should be enough for user IDs.

Some projects like Keycloak use string because they need to focus on performance and efficiency while turms do in every detail.

**Comment by itmagus** [comment]
嗯，明白，这两个ID要如何关联呢？需要在自己的应用中，维护两者的关联关系不？

**Comment by JamesChenX** [comment]
You don't have to associate these two IDs, and it just depends on your requirements of how to authenticate users.

**Comment by itmagus** [comment]
好的，谢谢
