### ISSUE TITLE
conversationService api

### ISSUE THREAD

**Issue by itmagus** [turms-im/turms#1020]
![image](https://user-images.githubusercontent.com/8073980/193211031-123e4a80-60dc-4b19-8c07-72a564febb60.png)
请问下，这个会话列表，在客户端的SDK里有对应的API吗？
应该如何实现比较正确？

**Comment by JamesChenX** [comment]
turms client APIs are designed to work for various use cases, so you need to orchestrate client APIs yourself.

## Example
You can reference and understand this example, but don't must follow it. Once you understand it, you can orchestrate client APIs yourself.

**Everytime** your client login successfully via `userService.login`, you can call:
1. `message.queryMessages({areGroupMessages: true, deliveryDateAfter: <last message date on the local client>})` for groups message
2. `message.queryMessages({areGroupMessages: false, deliveryDateAfter: <last message date on the local client>})` for private message
3. Now you have all new messages, so you have enough data to calculate the unread message count on your local client, and show the last message for each conversation.
4. The messages also contain the ID of the group or sender, so you can query the group/sender name/information by the ID on your local client cache.
If there is no cache on your local client (maybe it's a new device or whatever), you can send `userService.queryFriends({lastUpdatedDate: {last updated date on the local client})` to get friends' information, and `groupService.queryJoinedGroupInfos`.

You have got all information to display.

## IMPORTANT
1. It's highly recommended to store various `last updated date` on your local client, so that  your client can call APIs that have a parameter called `lastUpdatedDate` with the date to limit the query range.
2. Just remember the balance between latency and performance. In fact, you can cache a lot of things on your local client, so you need to send a lot of requests.

**Comment by itmagus** [comment]
![image](https://user-images.githubusercontent.com/8073980/193810455-edb468b5-e3bb-4ca0-9be9-622eac05ea12.png)
懂了，相当于，拿stream的SDK来说，现在的turms-im client sdk只做了api的部分，其他的部分，需要自己实现

**Comment by itmagus** [comment]
@JamesChenX 
还有Userinfo的信息怎么查啊，比如通过userService.queryFriends查到了用户关系，对应的联系人的信息怎么查呢，比如联系人的名称，好像没看到有对应的接口哈

**Comment by JamesChenX** [comment]
By default, turms do NOT enable querying oneself's messages like WeChat because of the performance reason mentioned in https://turms-im.github.io/docs/for-developers/schema.html#%E7%B4%A2%E5%BC%95.
And you can enable it by setting the property in turms-service: `turms.service.message.use-conversation-id=true`.
But there isn't a client API for it currently, I can deliver the feature in 3 days, and you can wait.


Use `queryUserProfile` to query the user's information.
By the way, `queryUserProfile` was designed to query only one user's information because of the performance reason, but I think it can be extended to query multiple users' profiles in some use cases. So if you need to do a batch query, you can wait and I can provide the feature today or tomorrow.

**Comment by itmagus** [comment]
好的，感谢，我可以等，对，userService.queryUserProfile，我需要的是可以批量查询
目前userinfo中没有头像的字段，也没看到有extraData可扩展之类的字段
不知道，应该如何正确的使用，如果采用约定的方式，存储在MINIO之类的上面，应该也是需要一个是否自定义头像的bool字段

**Comment by itmagus** [comment]
好的，感谢，我可以等，对，userService.queryUserProfile，我需要的是可以批量查询
目前userinfo中没有头像的字段，也没看到有extraData可扩展之类的字段
不知道，应该如何正确的使用，如果采用约定的方式，存储在MINIO之类的上面，应该也是需要一个是否自定义头像的bool字段

**Comment by itmagus** [comment]
好的，感谢，我可以等，对，userService.queryUserProfile，我需要的是可以批量查询
目前userinfo中没有头像的字段，也没看到有extraData可扩展之类的字段
不知道，应该如何正确的使用，如果采用约定的方式，存储在MINIO之类的上面，应该也是需要一个是否自定义头像的bool字段

**Comment by JamesChenX** [comment]
We don't plan to add something like `extra` in any collections currently because it's related to security problems and a lot of validation logic, and more complex properties. The field `extra` may be added in the future, but definitely not currently.

But, I can add a new string field like `profile` so that developers can use it as a profile URL, profile image ID, or even the BASE64-encoded profile image.

**Comment by itmagus** [comment]
嗯，挺好的

**Comment by itmagus** [comment]
@JamesChenX 
如果提交了记得说一下哈，谢谢

**Comment by itmagus** [comment]
> Don't worry, and I will @ you once the features are delivered.

好的

**Comment by JamesChenX** [comment]
@itmagus 1. The `queryUserProfile` has been adapted to `queryUserProfiles`, and you can query multiple user profiles in `develop` branch currently.
2. The new field `profilePicture` has been added to user models, and you can update it via the client API `updateProfile`. The format has no restrictions currently, and I will add some validation logic for it later.
3. The feature of querying messages sent by oneself hasn't been delivered, and I use another ticket (#1039) to trace it to not make this issue too large.

**Comment by itmagus** [comment]
好的，收到，有问题我再反馈咯

**Comment by JamesChenX** [comment]
@itmagus The feature `querying messages sent by oneself` has been delivered, and you can read #1039 for details.
