### ISSUE TITLE
message type

### ISSUE THREAD

**Issue by itmagus** [turms-im/turms#1052]
https://github.com/turms-im/turms/issues/831
请问下，消息类型怎么自定义或扩展，更遵循turms的使用原则
是通过在结构化text或records吗？后面不会影响搜索或其他的功能吧？
![image](https://user-images.githubusercontent.com/8073980/196850461-40e4b1cd-05d4-4880-8b43-e43a176700f0.png)

**Comment by JamesChenX** [comment]
The message type of turms is designed in a flexible way to meet various IM requirements (e.g. Put multiple pictures into a message, or mix different media records into a message.). And because it depends on how a client developer parses the message, you can save anything in `text` or `records` in fact according to your requirements.

> 通过在结构化text或records吗？后面不会影响搜索或其他的功能吧？

* It's okay to use a structured string (e.g. JSON) as the `text` of a message. And it won't affect the future advanced features (e.g. search. Though we don't plan to support it in v1.0.0) because we can sanitize the text and extract fields from it. So you don't need to worry about it.
* The message types provided by turms are just some templates (meaning you don't have to use them) encoded in an efficient way so that most developers don't have to write by themselves.
* `records` is mainly used to store binary data because it's inefficient to store binary data as `text` in BASE64.

**Comment by itmagus** [comment]
谢谢
