### ISSUE TITLE
deliveryDateAfter

### ISSUE THREAD

**Issue by itmagus** [turms-im/turms#1058]
client.messageService
        .queryMessagesWithTotal、queryMessages在传deliveryDateAfter时总会读最后一条消息，是否正常？
deliveryDateAfter在判断的时候是大于等于传过去的时间？
导致的问题是，在本地同步数据的时候，需要去判断和处理。
deliveryDateBefore是正常的，deliveryDateBefore是小于传过去的时间

**Comment by itmagus** [comment]
另外，queryMessagesWithTotal，在未传deliveryDateBefore,返回的messages，是最后一条消息，在传了deliveryDateBefore参数后，返回的是deliveryDateBefore后的第一条消息？

**Comment by itmagus** [comment]
@JamesChenX 这个问题计划调整吗？

**Comment by JamesChenX** [comment]
I am busy currently and will check it tomorrow.

**Comment by itmagus** [comment]
好的

**Comment by JamesChenX** [comment]
> queryMessagesWithTotal、queryMessages在传deliveryDateAfter时总会读最后一条消息，是否正常？

For example, if a user has messages from `1970` to `2022`, and the client pass `deliveryDateAfter` of the year `2000`, the first messages (`messages[0]`) will be in the year `2000`, and should get messages from `2000` to `2022`.

It's **expected**.

> 导致的问题是，在本地同步数据的时候，需要去判断和处理。

It's **expected** because turms is designed to support as many business scenarios as possible so turms client and server won't handle these data on the behalf of users, and users of turms clients can/should manage these data according to their business requirements.
btw, the logic to handle these data is simple, so don't be afraid.

> deliveryDateAfter在判断的时候是大于等于传过去的时间？

Yes. And all ranges that clients can pass follow `[min, max)` => `[deliveryDateAfter, deliveryDateBefore)`.

---

Just a reminder, I will enhance the `queryMessages(WithTotal)` APIs later (maybe this month) to support features like pagination, so you can wait for #1053 if you need them in your scenarios.

**Comment by JamesChenX** [comment]
> 另外，queryMessagesWithTotal，在未传deliveryDateBefore,返回的messages，是最后一条消息，在传了deliveryDateBefore参数后，返回的是deliveryDateBefore后的第一条消息？又因为是大于等于所以取本地哪条消息的时间传过去，返回的就是哪条消息？

After research, I think it's better to always sort messages by delivery date in an ascending order to not confuse users while keeping the business scenarios reasonable. And you can try it currently.

Thanks for your good suggestion.

**Comment by itmagus** [comment]
> After research, I think it's better to always sort messages by delivery date in an ascending order to not confuse users while keeping the business scenarios reasonable. And you can pull the latest code to try it currently.
> 

个人建议，默认可以统一为升序或降序，也可以根据需要指定升降序
await imProvider.client.messageService
        .queryMessagesWithTotal(
            areGroupMessages: false,deliveryDateAfter: deliveryDateAfter)
我这里想拿到的deliveryDateAfter之后的最近一条消息，而不是第一条消息

**Comment by JamesChenX** [comment]
> 个人建议，默认可以统一为升序或降序

For client messages, they are already always sorted by delivery date in ascending way.

> 根据需要指定升降序

Thanks for sharing your idea. It's accepted, and I will add a new parameter like `inDescendingOrder` in `queryMessages(WithTotal)` this week.

> 我这里想拿到的是deliveryDateAfter之后的最近一条消息，而不是第一条消息。我更新代码后，还是只能拿到deliveryDateAfter的第一条消息

You should better pass `last message delivery date - 15 seconds` as the `deliveryDateAfter`  so that you can ensure the client is likely to accept all messages in a distributed system, and you need to duplicate messages on the client side by yourselves, and the behavior is expected.
