### ISSUE TITLE
[QUESTION] how to use

### ISSUE THREAD

**Issue by l-7-l** [turms-im/turms#1121]
I plan to use js or rust to write a single service (I hate excessive abstraction, especially java and c# can't understand at all), provide user verification service, there seems to be no relevant documents, how should I do it
>我打算使用js或者rust写一个单体服务(我讨厌过度抽象， 尤其是java和c# 完全看不懂),提供用户校验服务， 貌似没有相关的文档 我应该如何去做呢

Is it feasible to store the message on the client and not save it on the server, and end-to-end encryption during the transmission process?
>把消息存储在客户端， 服务器不保存， 传输过程端到端加密可行吗

**Comment by JamesChenX** [comment]
1. For user identity access management, you can read the [doc](https://turms-im.github.io/docs/for-developers/client-identity-access-management.html). After you understand the doc, you can implement any server with your own business logic in your preferred programming languages, and use the server to call turms HTTP APIs.

2. If you want to store messages only on the client side, and not store them on the server side, you can set the property `turms.service.message.persist-message` to `false` (`true` by default) in `turms-service`

Note that: if you don't store messages on the server side, the messages are just lost if the users who should have received the messages are offline.

4. End-to-end encryption is supported via TLS, it's easy to support by the following steps:
   * For turms-gateway (server), configure the property group: `turms.gateway.websocket/tcp.ssl`
   * For turms-client-js, you don't need to configure it because using the URL with `https` is just enough.
   * For other clients, before you call `turmsClient.userService.login(...)` you need to call `turmsClient.userService.connect(useTls=true)` first. And it's done.

**Comment by l-7-l** [comment]
感谢兄百忙之中的解惑， 顺祝事业顺利 万事如意。

**Comment by l-7-l** [comment]
@JamesChenX  抱歉， 恕我有点蠢， 再请教一下:

- 在哪里指定公钥与私钥呢  生产环境最佳实践是什么

   > turms-gateway服务端拿到JWT令牌后，根据JWT令牌中指定的算法与开发者在turms-gateway服务端配置的公钥配置（非对称加密算法：RS256、RS384、RS512、PS256、PS384、PS512、ES256、ES384、ES512）或私钥配置（对称加密算法：HS256、HS384、HS512）对JWT令牌进行校验。

-   基于外部HTTP响应的身份与访问管理机制中工作流程提到， turms-gateway 会访问自有服务鉴权，这里自有服务地址怎么配置呢 

- turms.gateway.session.identity-access-management.type 相关配置文件在哪里

- 可以用 js|ts 写一个服务端最佳实践例子么

**Comment by l-7-l** [comment]
如果使用jwt是不是自有服务就不需要与turms交互了, 只需要配置公钥(如果是这样 公钥在哪里配置的)

**Comment by JamesChenX** [comment]
> 在哪里指定公钥与私钥呢

Configure them in `application.yaml` in turms-gateway. Read the doc: https://turms-im.github.io/docs/for-developers/client-identity-access-management.html#%E7%9B%B8%E5%85%B3%E9%85%8D%E7%BD%AE%E9%A1%B9-2

> 生产环境最佳实践是什么

`RS256` is good enough for most applications. For more details: https://security.stackexchange.com/questions/194830/recommended-asymmetric-algorithms-for-jwt

> 基于外部HTTP响应的身份与访问管理机制中工作流程提到， turms-gateway 会访问自有服务鉴权，这里自有服务地址怎么配置呢

Read the doc: https://turms-im.github.io/docs/for-developers/client-identity-access-management.html#%E5%86%85%E7%BD%AE%E7%9A%84%E8%BA%AB%E4%BB%BD%E4%B8%8E%E8%AE%BF%E9%97%AE%E7%AE%A1%E7%90%86%E6%9C%BA%E5%88%B6

> turms.gateway.session.identity-access-management.type 相关配置文件在哪里

`application.yaml` in turms-gateway

> 如果使用jwt是不是自有服务就不需要与turms交互了, 只需要配置公钥

Yes.

> 可以用 js|ts 写一个服务端最佳实践例子么

Pseudo code:
```js
httpServer.on('/my-endpoint', (request, response) => {
     const json = handle(request); // JSON format: https://turms-im.github.io/docs/for-developers/client-identity-access-management.html#%E5%86%85%E7%BD%AE%E7%9A%84%E8%BA%AB%E4%BB%BD%E4%B8%8E%E8%AE%BF%E9%97%AE%E7%AE%A1%E7%90%86%E6%9C%BA%E5%88%B6
     response.send(json);
})
```

> 是扔到common包的resources文件夹下边吧

1. You can configure it that way, but you must package it yourself. So it's not recommended.
2. If you use `docker` to run, you can environment variables to configure.
3. If you use `docker-compose` to run, you can use `volumes` to map your `applications.yaml` in the image.
**For more details, I will write a doc for it later when I am available.**
