### ISSUE TITLE
Is this correct for using redis statistics sessions？

### ISSUE THREAD

**Issue by LaZy1162999568** [turms-im/turms#1130]
local session_list_key = KEYS[1]
local session_id = KEYS[2]
local session_map_key = KEYS[3]
local session_key = KEYS[4]
local  status_key= KEYS[5]
local  status= KEYS[6]
local  top_key= KEYS[7]
local  top= KEYS[8]
local  msg_id_key= KEYS[9]
local  msg_id= KEYS[10]
local  type_key = KEYS[11]
local  type = KEYS[12]
local  target_key = KEYS[13]
local  target = KEYS[14]
local unread_key = KEYS[15]

-- 将会话添加到有序集合
redis.call('zadd', session_list_key, current_time, session_id)

-- 检查有序集合的大小是否超过限制
local size = redis.call('zcard', session_list_key)
if size > 100 then
  -- 删除最旧的会话
  redis.call('zremrangebyrank', session_list_key, 0, size-101)
end

-- 将会话的信息存入hash表
redis.call('hmset', session_map_key ,session_key, session_id, msg_id_key , msg_id,type_key, type,target_key,target)
redis.call('HSETNX',status_key,status)
redis.call('HSETNX',top_key,top)
-- 未读数自增
local unread = redis.call("HINCRBY", session_map_key, unread_key, 1)

![image](https://user-images.githubusercontent.com/38731460/217895839-2e42347f-452a-414f-abf7-4d7d1cc62f28.png)

**Comment by LaZy1162999568** [comment]
No instant messaging development experience, if you are free, please ask me, thank you

**Comment by JamesChenX** [comment]
Thanks for the idea sharing and the code.

**The task to support statistics in Turms is one of the most challenging tasks in fact, meaning you just picked the most difficult one, hhh**

---
It's feasible to use Redis to implement counting unread messages, and it's also what we will support in the future.

But from the code, it seems that you didn't design statistics features from the perspective of the whole system and business. For example, to implement counting unread messages, you also need to support the following features at least:
1. Support resetting count to 0, and when to reset.
2. Support removing related records in Redis when the user is deleted or the record expires (e.g. 1 year)

**So the features involve many things, and you need to understand both IM business and Turms code to deliver statistics features**.

---

For statistics for unread messages, your implementation isn't efficient, and I prefer the following data structure in Redis because it's more efficient:

| Key     | Field                           | Value |
| ------- | ------------------------------- | ----- |
| u123456 | g123456<br />(group, id=123456) | 123   |
|         | u123456<br />(user, id=123456)  | 100   |
|         | t<br />(total count)            | 223   |

Of course, the data structure above is just a draft, so it may change when deliver. So you can try to make a further optimization on it. 
If you have many efforts into it, you can give them a try, and I will help you when you encounter some problems.

**Comment by LaZy1162999568** [comment]
Thank you for taking time out of your busy schedule to reply to my question. As for the data of session, I consider that the server takes the initiative to create the latest session information when receiving a message, so that each message will request the cache. I am confused about whether the session list should be created by the client, or the client should take the initiative to request the server to create a latest session after receiving or sending a message. And thanks for your advice. It makes sense. I'll think about it carefully. thank you

**Comment by LaZy1162999568** [comment]
Also I want to know that the session unread should have expiration time in redis, so is there a good way to synchronize the session unread in the database

**Comment by JamesChenX** [comment]
btw, I think you means `conversation`, and not `session` (online session) in Turms.

* The client shouldn't need to maintain the conversation information on the server side, it's the business of the server.
* Save the unread message count in Redis is enough currently, so we don't need to care about the database. Just trying to keep the workflow and implementation simple in the first step.

I prefer an easier workflow:
1. If a user received a message, the server should always increase the conversation by 1.
2. If a user reads messages from a conversation, the server should return the message count between the time range (e.g. before 2000-01-01 10:10:10) sent by the client.
   **And we need the time range sent by the client because there is network delay between the client and the server. To get an accurate unread message count, we need the client to specify the time range.**
   So the previous draft data structure in Redis can't be used in this case because it doesn't record the message creation date, it won't support the query based on the time range.

3. The unread message couant is useful when the user is offline, and the server can send push notifications with the unread message count to the user when they receive a new message.

**Comment by lucky-lbc** [comment]
> btw, I think you means `conversation`, and not `session` (online session) in Turms.
> 
>     * The client shouldn't need to maintain the conversation information on the server side, it's the business of the server.
> 
>     * Save the unread message count in Redis is enough currently, so we don't need to care about the database. Just trying to keep the workflow and implementation simple in the first step.
> 
> 
> I prefer an easier workflow:
> 
>     1. If a user received a message, the server should always increase the conversation by 1.
> 
>     2. If a user reads messages from a conversation, the server should return the message count between the time range (e.g. before 2000-01-01 10:10:10) sent by the client.
>        **And we need the time range sent by the client because there is network delay between the client and the server. To get an accurate unread message count, we need the client to specify the time range.**
>        So the previous draft data structure in Redis can't be used in this case because it doesn't record the message creation date, it won't support the query based on the time range.
> 
>     3. The unread message count is useful when the user is offline, and the server can send push notifications with the unread message count to the user when they receive a new message.

bro . i have a question too.
If it is a group of 3000 people, sending a message requires updating 3000 person conversations, and using Redis to update these conversations is not appropriate？
