### ISSUE TITLE
群权限设置不生效

### ISSUE THREAD

**Issue by wushuangys** [turms-im/turms#1152]
您好，我用最新代码启用本地服务，群的权限是 ACCEPT_ANY_REQUEST,  使用turms-client-swift 加入群组显示成功后，查询群历史消息显示 code 5300 （不是群成员），在Admin的入群请求中可以查到入群请求

**Comment by JamesChenX** [comment]
Thanks for reporting.
The bug has been fixed. You can pull the latest code from the branches `develop` or `master` to have a try.
Currently, if the client sends a join request to a group with `ACCEPT_ANY_REQUEST` join strategy, it will join the group directly join a group member.

---

btw, the client may not receive group messages from a group if it just joined it because of the group member cache in turms-service. So it's recommended to pull messages themselves when the cache is used.
`turms.service.group.member-cache-expire-after-seconds` (15s by default)

---

And there is a related bug that users cannot approve group join requests, I will fix in another ticket: https://github.com/turms-im/turms/issues/1159
