### ISSUE TITLE
There are bugs in parsing messages in mongodb database

### ISSUE THREAD

**Issue by LaZy1162999568** [turms-im/turms#1196]
Message is full-parameter constructed, and the custom parser will report an error if mongo does not query all fields

Failed to decode the current Bson into the entity of the class: im.turms.service.domain.message.po.Message

![image](https://user-images.githubusercontent.com/38731460/230878398-5620795c-3065-42e3-9954-ccdfa63d224c.png)

**Comment by LaZy1162999568** [comment]
![image](https://user-images.githubusercontent.com/38731460/230878613-e8598ce4-b7c4-4fc0-95ff-9f1573ad7621.png)

**Comment by JamesChenX** [comment]
Thanks for reporting.

It should be fine to parse only a part of fields to an entity (e.g. `Message`).
1. If passing a wrong constructor param type, it should throw IllegalArgumentException with the message `argument type mismatch`;
2. If passing a wrong constructor param number, it should throw IllegalArgumentException with the message `wrong number of arguments`.
3. If passing a null value to a primitive field (e.g. bool, int, long instead of Boolean, Integer, Long), it should throw IllegalArgumentException without a message.

From your screenshot/logs, it seems that case 3, but `Message` has only Object fields and no primitive fields.
So, did you modify any code in Turms on your local machine?

---

If you didn't modify any code, could you help to debug it in this way?
1. Add the ① code on your local machine
2. Change the code as ② show
3. Set a breakpoint at ③
4. When the breakpoint triggers, you can know the real param values passed to the constructor, so that we can know what happen and fix it.

![image](https://user-images.githubusercontent.com/44962329/230903180-38df195c-98e8-47d3-8bbd-0ce1d0460511.png)

**Comment by LaZy1162999568** [comment]
![image](https://user-images.githubusercontent.com/38731460/231033863-e8895eda-0dfe-45cc-afad-cabfb6a21ded.png)
Message实体类字段是FInal修饰的，这似乎意味着在构造Message实体的时候需要初始化所有字段

![image](https://user-images.githubusercontent.com/38731460/231034372-641dd7b2-8182-44bb-881d-e131ad12be77.png)
如这个代码，在修改消息请求时，会通过消息id查询这条消息的发送时间
![image](https://user-images.githubusercontent.com/38731460/231036196-91d926d1-1b0b-475b-b55b-19be9929a636.png)

我有修改过代码，但是我认为应该不是我修改代码产生的问题，目前我是把final修饰去掉了，在添加一个无参构造函数，则会通过initInstance(instance, reader, decoderContext);  使用set方式赋值。抱歉我英语不好

**Comment by LaZy1162999568** [comment]
额 抱歉 刚刚看到我Message实体类中 我添加了一个基础类型字段，所以存在此错误。

**Comment by JamesChenX** [comment]
> 额 抱歉 刚刚看到我Message实体类中 我添加了一个基础类型字段，所以存在此错误。

Yes. That's the case 3 that I mentioned above.
