### ISSUE TITLE
I have a question about message storage

### ISSUE THREAD

**Issue by LaZy1162999568** [turms-im/turms#1198]
I read a lot of articles on the Internet where they mention offline message libraries and message history libraries

The offline library stores all offline messages that are delivered to users during login

The history library is used for message roaming when a new device logs in

But only one message history library is used in turms

Although I probably know the function of offline library, it seems that history library can directly replace offline library. Is offline library still needed in turms? If so, what is its function and if not, why?

Could you take a moment to answer that? Thank you.

我看很多网络上的文章他们都 有提到过消息离线库和消息历史库
离线库存储离线消息用于登录时向用户下发的全量离线消息
历史库用于新设备登录时的消息漫游
但在turms中只使用了一个消息历史库
虽然我可能大概知道离线库的作用，但是历史库似乎可以直接替代离线库，那在turms中是否还需要离线库呢，如果需要他的作用是什么，如果不需要，为什么；
您能浪费点时间解答下吗，谢谢了。

**Comment by JamesChenX** [comment]
I think you are asking about the advantages and disadvantages of fan-out read and fan-out write.
I have already written a doc for it, and you can read it: https://turms-im.github.io/docs/for-developers/status-aware.html#%E8%AF%BB%E6%89%A9%E6%95%A3%E4%B8%8E%E5%86%99%E6%89%A9%E6%95%A3

In short, if you (or anyone else) does not master IM business and know 100% details of what you are designing, you should always use fan-out read.

**Comment by LaZy1162999568** [comment]
我想读扩散和离线消息库应该是两个东西吧，因为读写扩散是消息存储以及查询的方式，而离线消息库用户离线期间收到的所有消息，顺便我还想再问个问题。在turms 多端登录中是否存在 当redis没有清除掉当WEB端在线而IOS端离线，并且IOS离线后redis中的IOS端的用户登录节点信息并没有清除，因为存储的结构hash无法对field设置过期时间，导致在全部登录设备离线之前，获取到的IOS在线状态就是一直在线，并且如果中途重启了gateway 会导致获取到的用户节点信息不正确

**Comment by LaZy1162999568** [comment]
用户登录状态信息在redis中的有效时间是3分钟，假设我在3分钟内重启gateway，此时redis中的用户登录信息是不会清除掉的，如果此时其中的某个端登录那么将更新这个hash 键的存活时间，但是对于没有重连的设备，那么获取到的用户节点信息就不正确。

另外：我在开发过程中发现偶尔在服务器重启后，客户端登录会提示：
SESSION_SIMULTANEOUS_CONFLICTS_OFFLINE(2102, "A different device has logged into your account", 409)
我将redis脚本修改为如下，是否会因为这个导致这一系列问题

![image](https://user-images.githubusercontent.com/38731460/231331835-3632d823-719b-4b54-ad63-72562178fe22.png)

**Comment by JamesChenX** [comment]
> 我想读扩散和离线消息库应该是两个东西吧，因为读写扩散是消息存储以及查询的方式，而离线消息库用户离线期间收到的所有消息

The advantages and disadvantages of introducing a table/collection for `offline messages` are different for fan-out read and fan-out write. In short, it's a shortsighted design for most cases.

**Comment by JamesChenX** [comment]
> 用户登录状态信息在redis中的有效时间是3分钟，假设我在3分钟内重启gateway，此时redis中的用户登录信息是不会清除掉的

If turms-gateway servers are closed gracefully (instead of forcibly), servers will remove related local online statuses on Redis when closing as I mentioned above.

> 如果此时其中的某个端登录那么将更新这个hash 键的存活时间，但是对于没有重连的设备，那么获取到的用户节点信息就不正确。

That's also a good point, and I have realized the problem and created ticket #1022.
`If you are interested in it, you can try to enhance it to design a workflow to handle these outdated online statuses`. Otherwise, I will handle related issues after 1~3 month(s) because I am busy with a lot of things.

> 我在开发过程中发现偶尔在服务器重启后，客户端登录会提示：
SESSION_SIMULTANEOUS_CONFLICTS_OFFLINE(2102, "A different device has logged into your account", 409)
我将redis脚本修改为如下，是否会因为这个导致这一系列问题

No. It's fine for turms-gateway to respond with `SESSION_SIMULTANEOUS_CONFLICTS_OFFLINE` for outdated online statuses if you know how turms-gateway works.
But as we discussed above, we can enhance related workflow as mentioned above to reduce outdated online statuses though outdated online statuses will still exist in edge cases after the above enhancements.

**Comment by LaZy1162999568** [comment]
好的 谢谢。turms代码有点高深。我都看不大懂
