### ISSUE TITLE
用户切换设备能否同步历史会话？

### ISSUE THREAD

**Issue by Enan01** [turms-im/turms#1210]
用户在A设备上存在单聊和群聊会话，如果切换到B设备上，这些会话能否同步？

为什么会问这个问题，因为目前turms采用读扩散方式存储消息，需要客户端主动去拉取每个会话的消息来做消息同步，但是我发现目前客户端的 `messageService` 提供的 `queryMessages` 方法查询消息，这个方法需要提供一些查询条件，对于切换设备的场景，第一次登录本地不存在任何会话，无法获取到对应的条件，如何才能查询到历史会话？

**Comment by JamesChenX** [comment]
Yes. The feature is already supported, and you can implement it very easily.
Just passing the parameters `areGroupMessages` and `deliveryDateStart` when calling `queryMessages` so you can query the messages in any delivery time range.

**Comment by Enan01** [comment]
> Yes. The feature is already supported, and you can implement it very easily. Just passing the parameters `areGroupMessages` and `deliveryDateStart` when calling `queryMessages` so you can query the messages in any delivery time range. For example, if `areGroupMessages` is true and `deliveryDateStart` is `2000-01-01 00:00:00`, then Turms server will return group messages after `2000-01-01 00:00:00`

对于群聊会话，这样是可以的。但是对于单聊会话，好像不可行。我是通过服务端处理客户端发送的 `QueryMessagesRequest` 请求函数调用栈来分析的。

分析的结论：

当满足条件 `areGroupMessages == false && from_ids == null` 时，只会查询出接收方为当前用户的消息，无法查询出发送方为当前用户的消息。

分析的过程：

服务端处理 `QueryMessagesRequest` 请求的 handler 如下：

`im.turms.service.domain.message.access.servicerequest.controller.MessageServiceController#handleQueryMessagesRequest`

通过 `Long userId = clientRequest.userId();` 获取到发起请求的用户id，`userId` 会传入 `im.turms.service.domain.message.service.MessageService#authAndQueryCompleteMessages` 方法中的 `requesterId` 参数。

之后会将 `requesterId` 继续传递到 `im.turms.service.domain.message.service.MessageService#queryMessages` 方法中的 `targetIds` 参数中。

最终 `targetIds` 会传递给 `im.turms.service.domain.message.repository.MessageRepository#findMessages` 方法中的 `targetIds` 参数。

查询 Mongo 的条件为 `tid in (targetIds)`，所以返回的结果为消息接收方为当前用户的消息。

如果我的分析有问题，希望能够指出，谢谢！

**Comment by JamesChenX** [comment]
A part of your understanding is correct:
* By default, it's true that turms only support querying messages sent by oneself in private conversations. Turms use this design as a default design because it has better throughput.
* But users can set the `turms.service.message.use-conversation-id` property to `true` (`false` by default) to support querying all messages in private conversations no matter whether the messages are sent by oneself or others.

And you can check the implementation for details: `im.turms.service.domain.message.service.MessageService#queryMessages`

**Comment by Enan01** [comment]
> A part of your understanding is correct:
> 
> * By default, it's true that turms only support querying messages sent by oneself in private conversations. Turms use this design as a default design because it has better throughput.
> * But users can set the `turms.service.message.use-conversation-id` property to `true` (`false` by default) to support querying all messages in private conversations no matter whether the messages are sent by oneself or others.
> 
> And you can check the implementation for details: `im.turms.service.domain.message.service.MessageService#queryMessages`

是的，当 `turms.service.message.use-conversation-id == true && areGroupMessages == false && from_ids != null` 时，可以查出消息发送人和消息接收人是当前用户的消息。

我现在的疑惑是，当 `from_ids == null`，如何查出用户历史的单聊会话？

**Comment by JamesChenX** [comment]
@Enan01 The client should pass `from_ids` for performance reasons so that turms server doesn't need to query `target_ids` to reduce one query to MongoDB.
And the client should already know `from_ids` because the client should query its contacts first, and then query messages.

btw, I will update and add more query filter params for `queryMessages` later because some parameter names are confusing.

**Comment by cqzongjian** [comment]
请问如何修改 turms.service.message.use-conversation-id 为 true @JamesChenX @Enan01

**Comment by JamesChenX** [comment]
Hi @cqzongjian , Turms has a detailed doc on configuration.
You can read it:
English: https://turms-im.github.io/docs/server/deployment/config.html
Chinese: https://turms-im.github.io/docs/zh-CN/server/deployment/config.html
