### ISSUE TITLE
An error occurred when creating a group；

### ISSUE THREAD

**Issue by yxp0208** [turms-im/turms#1239]
![image](https://github.com/turms-im/turms/assets/75196621/4db7dcfc-5095-4f72-9d6b-83853845eb52)
Client to create a group times this error, is the library does not have this user, how to add this user.

**Comment by JamesChenX** [comment]
## Root Cause
From my experience, this may happen if you create users without calling the HTTP endpoint `POST /users`.
In other words, you may use your own authentication plugin or set `turms.gateway.session.identity-access-management.enabled` set to `false`.

And when these clients (whose data are not persisted in MongoDB) try to create a group, turms-service will check whether the user is authorized to create, but turms-service cannot find their user record in MongoDB, so the server throws 2400 as you mentioned.

## Solution
To enhance the related workflow for users without persisting users' data in MongoDB, I will add related properties so that you won't meet such problems **this week**.
