### ISSUE TITLE
createGroup return Unhandled Exception: 1685915268:3100:The requester is only allowed to create groups with the types: [0]:null:null

### ISSUE THREAD

**Issue by weishirongzhen** [turms-im/turms#1249]
create a new group type in admin page, then call
`client.groupService.createGroup(groupName,typeId:2432292779693449216.toInt64());`

to create a new group,

will return `Unhandled Exception: 1685915268:3100:The requester is only allowed to create groups with the types: [0]:null:null`

how to allow all users can creategroup with new group type except default typeid 0. 

<img width="1555" alt="image" src="https://github.com/turms-im/turms/assets/54241621/d9ece04a-23a6-4f3c-8f7d-8be15ab53e4c">

and I found some config in:
<img width="1498" alt="image" src="https://github.com/turms-im/turms/assets/54241621/8eed4d59-43c6-4b98-ae8a-341388b5e031">

how can I config single user be able to create multi group types?

**Comment by JamesChenX** [comment]
> how to allow all users can creategroup with new group type except default typeid 0

Because all users are in the default permission group (the group with ID `0`) by default, you can select the default permission group under the `Permission Group` tab,  and then click `Update Selected Permission Groups` button, and input the group IDs that you want to allowed like `[1,2,3]`, and click OK.
![image](https://github.com/turms-im/turms/assets/44962329/70648f22-1efb-4dca-9166-cc0cfe9d2b1c)

> how can I config single user be able to create multi group types

You can create a new permission group for the user.
And assign the permission group ID for the user as follows:

![image](https://github.com/turms-im/turms/assets/44962329/8c50ea35-d41e-4543-9de7-5c50dcf49fdf)
