### ISSUE TITLE
group profile picture issue

### ISSUE THREAD

**Issue by weishirongzhen** [turms-im/turms#1257]
when create group or update a group
```
groupService.updateGroup(Int64 groupId,
      {String? name,
      String? intro,
      String? announcement,
      int? minScore,
      Int64? typeId,
      DateTime? muteEndDate,
      Int64? successorId,
      bool? quitAfterTransfer})
```

there is no profilePicture parameter, but in storageService, uploadGroupProfilePicture is provided,
is it group profile picture is missing in api design?

**Comment by JamesChenX** [comment]
If you want to manage group profile pictures (or other storage resources) by Turms, the API design is fine because:
* `groupService` is mainly used to manage data in the group domain, and `storageService` is mainly used to manage data for groups, users, and messages. in the storage resources domain.
* If you upload resources by `storageService`, it's meanless for you to update the profile picture URL of a group to a custom URL because you can either interfere with the profile picture URLs provided by Turms if you decide to use regular profile picture URLs, or you need to call `queryGroupProfilePicture` to get the URL if you decide to use inregular profile picture URLs for anti-crawler reasons.

But if you want the storage resources by other services (not Turms), it's reasonable to update the profile picture via `updateGroup`, and I can update the API to add a param like `profilePicture` for you if you want.

**Comment by weishirongzhen** [comment]
thanks for explaination, I can use queryGroupProfilePicture to achieve what I need.

why I hava this issue is influence by userService.updateProfile api :
<img width="689" alt="image" src="https://github.com/turms-im/turms/assets/54241621/e93de397-2947-4eb3-8775-5bb237ff0500">
has a param to save profilePicture value
