### ISSUE TITLE
redis的相关配置没有生效

### ISSUE THREAD

**Issue by wangqingchengsg** [turms-im/turms#1280]
配置参数如下:
-Dturms.gateway.redis.session.uri-list[0]=redis://127.0.0.1:6379
-Dturms.gateway.redis.location.uri-list[0]=redis://127.0.0.1:6379
-Dturms.gateway.redis.ip-blocklist.uri=redis://127.0.0.1:6379
-Dturms.gateway.redis.user-blocklist.uri=redis://127.0.0.1:6379

启动报错。。。连接的是代码里面写死的地址，令我很费解

**Comment by JamesChenX** [comment]
> 启动报错

If I tell you `it's funny`, can you guess what `it` refer to? So do I.

> 连接的是代码里面写死的地址，令我很费解

It's a thing that I don't know even though I have developed Turms for years.

Please read the doc for Turms configuration so that you can know how to configure it correctly:
English: https://turms-im.github.io/docs/server/deployment/config.html
Chinese: https://turms-im.github.io/docs/zh-CN/server/deployment/config.html
