### ISSUE TITLE
序列化和反序列化问题

### ISSUE THREAD

**Issue by wangqingchengsg** [turms-im/turms#1291]
cpu使用率低，流量低的时候，，所有业务都正常，压测的时候 就会大量报这种错误
![image](https://github.com/turms-im/turms/assets/22829954/04679526-6009-4eaa-b621-c54b366ef8d1)

![image](https://github.com/turms-im/turms/assets/22829954/a8403c18-fe2e-4c40-bc0e-137808f5a909)

![image](https://github.com/turms-im/turms/assets/22829954/01a8282d-46a9-466d-90b9-7188cde32741)

![image](https://github.com/turms-im/turms/assets/22829954/6567a857-c4f0-4472-94a5-1a17225b6067)

**Comment by wangqingchengsg** [comment]
我们已经使用很久了，现在一直有这种问题，最近很频繁。。。能否帮忙看看？ 大佬

**Comment by JamesChenX** [comment]
> 进行了大量的业务处理，所以不能也不敢升级

btw, that's why I recommend users commit their changes back to Turms if possible in the doc:
[about-upstream-first](https://turms-im.github.io/docs/community/#about-upstream-first)
[关于“上游优先”](https://turms-im.github.io/docs/zh-CN/community/#%E5%85%B3%E4%BA%8E-%E4%B8%8A%E6%B8%B8%E4%BC%98%E5%85%88).

> 现在一直有这种问题，最近很频繁

Your Turms servers seem quite old, and I have fixed tens of bugs including this bug since you posted the issue.

For upgrading (using the latest code on `master` branch, or the latest images), I am sure there is no breaking change in the collection schema, which means your data stored in MongoDB collections will still work as usual after upgrading.
But there are some breaking changes in status codes (e.g. code names change), and the proto models,
so:
### If you can upgrade both Turms client SDK and servers, you SHOULD upgrade them all together. You should NOT just upgrade one of them.
### If you plan to never upgrade Turms, you can try your luck to copy the code under `im.turms.server.common.storage.mongo.codec.EntityCodec` to your codebase, but I cannot promise it can fix the bug. And I have no plan to provide support for users who plan to never upgrade because if users plan to not upgrade, they should maintain their code for themselves.

**Comment by wangqingchengsg** [comment]
1.大佬，您说你改过的包含这个bug,那大概改动的哪一块，是否可以具体一点，这样我好有个方向
2.大佬，我如果覆盖序列化和反序列化的代码，我需要使用官方的哪个分支进行覆盖？

跪谢大佬，跪谢大佬，跪谢大佬



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月16日 21:35 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [turms-im/turms] 序列化和反序列化问题 (Issue #1291) |

进行了大量的业务处理，所以不能也不敢升级

btw, that's why I recommend users commit their changes back to Turms if possible in the doc:
about-upstream-first
关于“上游优先”.

现在一直有这种问题，最近很频繁

Your Turms servers seem quite old, and I have fixed tens of bugs including this bug since you posted the issue.

For upgrading (using the latest code on master branch, or the latest images), I am sure there is no breaking change in the collection schema, which means your data stored in MongoDB collections will still work as usual after upgrading.
But there are some breaking changes in status codes (e.g. code names change), and the proto models,
so:

If you can upgrade both Turms client SDK and servers, you SHOULD upgrade them all together. You should NOT just upgrade one of them.
If you plan to never upgrade Turms, you can try your luck to copy the code under im.turms.server.common.storage.mongo.codec.EntityCodec to your codebase, but I cannot promise it can fix the bug. And I have no plan to provide support for users who plan to never upgrade because if users plan to not upgrade, they should maintain their code for themselves.

**Comment by JamesChenX** [comment]
> 您说你改过的包含这个bug,那大概改动的哪一块，是否可以具体一点

The class may be `im.turms.server.common.storage.mongo.codec.EntityCodec`. After you paste the code, if the bug still exists, you can try to copy all classes under `im.turms.server.common.storage.mongo.codec` package.

btw, if you know how to modify the Turms source code, it should be easy for you to apply the changes under `im.turms.server.common.storage.mongo.codec` package.

> 我如果覆盖序列化和反序列化的代码，我需要使用官方的哪个分支进行覆盖？

Use the `master` branch, which is a stable branch.

btw, if you have lost all git commits in Turms repo, I suggest you first pull the Turms repo, check out the `master` branch, and then just take time and patience to merge your changed code.
It's a good practice to write your tests to ensure your modified code can work as expected so that you don't need to be "afraid" of upgrading Turms.

**Comment by wangqingchengsg** [comment]
![image](https://github.com/turms-im/turms/assets/22829954/95a04cf5-6fe3-470c-8baf-baf84672ec9a)
1是现在正在使用的
2是master上的代码
大佬，我发现出现上述问题的错误的代码，都在使用1这个方法，请问下和这个是否有关系？

**Comment by wangqingchengsg** [comment]
嗯嗯，谢谢大佬哈



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月16日 23:17 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [turms-im/turms] 序列化和反序列化问题 (Issue #1291) |

您说你改过的包含这个bug,那大概改动的哪一块，是否可以具体一点

The class may be im.turms.server.common.storage.mongo.codec.EntityCodec. After you paste the code, if the bug still exists, you can try to copy all classes under im.turms.server.common.storage.mongo.codec package.

btw, if you know how to modify the Turms source code, it should be easy for you to apply the changes under im.turms.server.common.storage.mongo.codec package.

我如果覆盖序列化和反序列化的代码，我需要使用官方的哪个分支进行覆盖？

Use the master branch, which is a stable branch.

btw, if you have lost all git commits in Turms repo, I suggest you first pull the Turms repo, check out the master branch, and then just take time and patience to merge your changed code.
It's a good practice to write your tests to ensure your modified code can work as expected so that you don't need to be "afraid" of upgrading Turms.
