### ISSUE TITLE
Do you support uni-app development access?

### ISSUE THREAD

**Issue by yxp0208** [turms-im/turms#1304]
Use uni-app to develop small programs, want to access instant messaging function, can support?

**Comment by JamesChenX** [comment]
Sorry, we have no plan to support solutions such as uni-app, taro, WeChat mini-programs, etc.
There are many reasons, e.g.:
1. We prefer to keep Turms client SDK simplified, and not to be involved with other application solutions.
2. Most of the time, we hold different project management philosophies.

   For me, I have a fundamental thinking about project management. That is `create users' success` instead of `create my success`.
Some people have a qualified ability, but they are greedy for their own success (money, promotion, etc.), and do not care about users' success, and will just create terrible projects even though their projects may be influential. There are countless projects maintained by this kind of people.

   We prefer to work with mature people and their projects, just because they are trustworthy and know the power of respect for users and responsibility for their own projects.
