### ISSUE TITLE
启动TurmsGatewayApplication和TurmsServiceApplication时,会报错:im.turms.server.common.infra.address.NoAvailableAddressFoundException: Failed to detect the local IP

### ISSUE THREAD

**Issue by reubencharles842** [turms-im/turms#1305]
启动时报错:

im.turms.server.common.infra.address.NoAvailableAddressFoundException: Failed to detect the local IP

caused by: im.turms.server.common.infra.address.NoAvailableAddressFoundException: The IP address (198.18.0.1) is not a site local IP address

**Comment by JamesChenX** [comment]
It's expected.
When a turms server runs, it will register its IP for RPC communication.
By default, turms server uses the private IP (or site-local IP) that should be in the range of 10.0.0.0/8, 192.168.0.0/16, 172.16.0.0/12, but your IP (198.18.0.1) is used for inter-network communications ()
isn't in that range, so the server just throws, and it's expected.

1. You can set the property `turms.cluster.discovery.address.advertise-strategy=public_address` to make turms server use the public address instead of the private address, or you can set `turms.cluster.discovery.address.advertise-strategy=advertise_address` and `turms.cluster.discovery.address.advertise-host=<any_ip>`
2. Or you can just close your proxy and try again if your proxy was enabled.
