### ISSUE TITLE
how to @someone within a message

### ISSUE THREAD

**Issue by weishirongzhen** [turms-im/turms#1310]
I only found a desc in doc, but can not found related api in code 
`
| @someone                                               | is used to specifically remind a user. If the Turms client detects that the user @ in the received message is currently logged in, the Turms client will trigger the @ callback function. Developers can implement subsequent related business logic by themselves. It is often used to remind users who are @. <br />There is no essential difference between the @ message in the group and the ordinary message, only that when the @ message is received, special processing is required (triggering a callback function) |        `                                                      |

**Comment by JamesChenX** [comment]
The feature of `@someone` is called `mention` officially.
The `mention` feature is implemented as a client feature instead of a server feature (just think about Markdown-based chat messages), which means it's up to the client developers to decide how to `mention` in a chat message, and has nothing to do with servers.

But all turms clients provide a default `mention` implementation/parser, so you can use it if you think it's okay for your applications.
You can use the default implementation by:
1. Calls `turmsClient.messageService.enableMention()`, which will use the default mention parser.
2. Calls:
```
turmsClient.messageService.addMessageListener((message, messageAddition) => {
    messageAddition.isMentioned; // whether the current user is mentioned
    messageAddition.mentionedUserIds; // Who are mentioned in the message
})
```

**Comment by weishirongzhen** [comment]
`turmsClient.messageService.enableMention() `is call on sender side or recipent side?

**Comment by JamesChenX** [comment]
If a client needs to parse `metioned user IDs` from a chat message, the client should call it to enable.
So in most cases, clients in the same application should use the same logic, if a client enables `mention`, all of them should enable it. Of course, this is up to the client developers.

**Comment by JamesChenX** [comment]
Just think about GitHub issue comments, we can send `styles` using Markdown-based chat message string.
It's the same for how to parse `mentioned user IDs` from a chat message. e.g. `I need to talk with @{123} and @{321}`.
