### ISSUE TITLE
The Block Date of User Relationship cannot be reset to null

### ISSUE THREAD

**Issue by zy2203** [turms-im/turms#1324]
At project `turms-client-dart`, run this code, the `Block Date` cannot be reset to null.
```dart
await client.userService.updateRelationship(Int64(2), isBlocked: false);
```

And in the turms admin, Update Relationships like this, also cannot be reset to null.
![1698142416622](https://github.com/turms-im/turms/assets/54758962/bf432cf5-6adb-419b-8350-d74d1cfea301)

I see the code method name is `setOrUnsetDate`. But when `date==null`, do not execute `appendUnset(field)`.
![1698142565125](https://github.com/turms-im/turms/assets/54758962/bebcb6d1-20db-48f1-8af4-7afe3e1cfe60)
![1698142621650](https://github.com/turms-im/turms/assets/54758962/f6d64891-69d6-4f15-acde-5d9cf7f7966b)

so i change the code, at turms admin Update Relationships is working. Can this be done?
```java
public Update setOrUnsetDate(String field, Date date) {
    if (date != null && date.getTime() > 0) {
        appendSet(field, date);
    } else {
        appendUnset(field);
    }
    return this;
}
```

**Comment by JamesChenX** [comment]
Thanks for reporting.
1. For the problem that `client.userService.updateRelationship(Int64(2), isBlocked: false);` doesn't work, it is a bug and **the bug fix will be published tomorrow**.
2. `And in the turms admin, Update Relationships like this, also cannot be reset to null`, which is a problem of UI design, you can pick a date time before or at '1970-01-01 00:00:00Z' in `Block Time` form field to unblock a user for now.
I will polish the UI but may not recently just because it's a low-priority UI enhancement.
