### ISSUE TITLE
能否使用scyllaDB替换mongodb?

### ISSUE THREAD

**Issue by xs-abscd** [turms-im/turms#1328]
我想使用scyllaDB替换mongodb，我看到手动搭建与启动里面数据库和docker是可以分开部署的，那么我能否把这里的mongoDB换成scyllaDB，以及需要哪些配置呢？

**Comment by JamesChenX** [comment]
I think this is a common request that some users may want to replace MongoDB with other databases.
Some IM solutions may advertise that they can support a lot of kinds of databases, but it just means the IM solution is too simple so that they can work on any kind of database.

---

It's not practical for Turms servers to use other kind of database because Turms servers use a lot of "advanced" features of MongoDB, e.g.:
1. Distributed transactions (even across multiple collections)
2. Partial index
3. Sharding collections

And we also code for MongoDB optimally.
So it's impractical to replace MongoDB with any kind of database even Amazon DynamoDB.

**Comment by xs-abscd** [comment]
> I think this is a common request that some users may want to replace MongoDB with other databases. Some IM solutions may advertise that they can support a lot of kinds of databases, but it just means the IM solution is too simple so that they can work on any kind of database.
> 
> It's not practical for Turms servers to use other kind of database because Turms servers use a lot of "advanced" features of MongoDB, e.g.:
> 
> 1. Distributed transactions (even across multiple collections)
> 2. Partial index
> 3. Sharding collections
> 
> And we also code for MongoDB optimally. So it's impractical to replace MongoDB with any kind of database even Amazon DynamoDB.

谢谢，基于您的建议是不要使用其他类型的数据库替换MongoDB。因为程序代码中大量使用了MongoDB的特性，那么是否意味着，通过对turms的二次开发可以实现替换数据库的想法，这个工作量是否非常巨大？

**Comment by JamesChenX** [comment]
It's a downgrade to replace MongoDB with ScyllaDB for Turms servers, so I highly recommend you **NOT** to do so.

If you really want to replace MongoDB with ScyllaDB, you need to remove a lot of features supported by MongoDB and implement all code under the package `storage/mongo` with a simple storage implementation based on ScyllaDB (ScyllaDB is limited for OLTP use cases), and then your implementation is probably never compatible with future updates of Turms.
It may take 1~3 months for a full-time senior engineer to migrate and test.

**So in a word, if you have to use ScyllaDB for your applications, it may be a better choice to reference Turms to write your own IM  solution.**
