### ISSUE TITLE
查询语句是否可以支持下$expr语法

### ISSUE THREAD

**Issue by wangqingchengsg** [turms-im/turms#1346]
查询语句是否可以支持下$expr语法

im.turms.server.common.storage.mongo.operation.option.Filter 这个类中是否可以支持$expr等其他语法

**Comment by JamesChenX** [comment]
Hi @wangqingchengsg, 
I do not quite understand your requirements.
If you just want to add some methods in `im.turms.server.common.storage.mongo.operation.option.Filter`, feel free to do.
But it's meaningless to add these methods without using them.

**So do you mean you want to support some MongoDB built-in expressions like `$expr` for admin HTTP APIs?**

If so, please tell me about your specific business requirements so that I can ensure new features can work for you while they can be implemented flexibly for future enhancements.
