### ISSUE TITLE
Information consultation

### ISSUE THREAD

**Issue by kf53916** [turms-im/turms#1367]
1.The functionality is not very complete, lacking a response strategy for adding friends, a response strategy for group invitations, and a interface for creating sessions
2.What is the difference between createRelation, createFriendRelationship, and sendFriendRequest
3.How to integrate the user system of existing business systems?
4.Is the password not encrypted and transmitted directly in plaintext?

**Comment by JamesChenX** [comment]
> 1.The functionality is not very complete

All features you mentioned are supported. Read the source code of client APIs to know how to respond to these requests, you should be able to judge from their method names, or wait for me to write a doc for them this week or next week when I am not that busy (I am busy with implementing the UI of turms-chat-demo).

> 2. What is the difference between createRelation, createFriendRelationship, and sendFriendRequest

`createFriendRelationship` is a helper method of `createRelationship`, see:
![image](https://github.com/turms-im/turms/assets/44962329/1df4ceac-1d8c-4cb1-b3d7-cfd81f8b3ea2)

The difference between `createRelationship` and `sendFriendRequest` is that: Depends on custom properties(as you may know , Turms supports hundreds of properties to configure your business scnerios), Turms supports allowing clients to create a relationship directly via `createRelationship` without the need to send a friend request, and also support requiring clients sending a friend request and must not create a relationship directly (If happened, Turms will respond with an error code).

**For details, wait for me to write a doc.**

3. How to integrate the user system of existing business systems?

https://turms-im.github.io/docs/server/module/identity-access-management.html

4. Is the password not encrypted and transmitted directly in plaintext?

turms-client-dart/js/kotlin/swift support TLS, and it's enough for encryption.
turms-client-cpp doesn't support TLS just because I don't have time for it.

Bonus: e2ee (End-to-end encryption) is not support for all clients.
