### ISSUE TITLE
2100 code show unexpected.

### ISSUE THREAD

**Issue by weishirongzhen** [turms-im/turms#1384]
`SESSION_SIMULTANEOUS_CONFLICTS_DECLINE(2100, "A different device has logged into your account",409),
`

When I reboot service and gateway, when server is not fully started, then client login sometimes code 2100 will show.

**Comment by JamesChenX** [comment]
This may happen if:
1. A turms-gateway server was shut down abruptly (not shut down gracefully), which caused the server not to have the chance to delete online sessions managed by it on Redis.
2. If a new turms-gateway is starting or started while the outdated online sessions are still not expired (60s by default, you can control it by setting `turms.user-status.user-sessions-status-expire-after`), the same user tries to log in with the device type same with the previous device type, turms-gateway will respond with the code `SESSION_SIMULTANEOUS_CONFLICTS_DECLINE` to indicate the session of the same device type is still online because the previous online session info still exists on Redis.
3. In this case, the user has to wait for the online session to expire and to be deleted by Redis automatically.

**Comment by weishirongzhen** [comment]
Thanks for explanation
