### ISSUE TITLE
how to config plugin config Properties in yml ， please for example !

### ISSUE THREAD

**Issue by zhaieryuan** [turms-im/turms#1407]
1、我把敏感词汇的配置放在 turms-plugin-antispam 的 resources 目录application.yaml下，服务启动turms_service ，报错:
**************************
APPLICATION FAILED TO START
***************************

Description:

Binding to target [Bindable@5d8ab698 type = im.turms.server.common.infra.property.TurmsProperties, value = 'provided', annotations = array<Annotation>[@org.springframework.boot.context.properties.ConfigurationProperties(ignoreInvalidFields=false, ignoreUnknownFields=false, prefix="turms", value="turms")], bindMethod = JAVA_BEAN] failed:

    Property: turms.plugin.antispam.dictparsing.skipinvalidcharacter
    Value: "true"
    Origin: class path resource [application.yaml] - 55:31
    Reason: The elements [turms.plugin.antispam.dictparsing.skipinvalidcharacter,turms.plugin.antispam.dictparsing.textfilecharset,turms.plugin.antispam.dictparsing.textfilepath,turms.plugin.antispam.enabled] were left unbound.
    Property: turms.plugin.antispam.dictparsing.textfilecharset
    Value: "UTF-8"
    Origin: class path resource [application.yaml] - 54:26
    Reason: The elements [turms.plugin.antispam.dictparsing.skipinvalidcharacter,turms.plugin.antispam.dictparsing.textfilecharset,turms.plugin.antispam.dictparsing.textfilepath,turms.plugin.antispam.enabled] were left unbound.
    Property: turms.plugin.antispam.dictparsing.textfilepath

2、同上我把配置放在 turms-service 的 resources 目录application.yaml下，服务启动turms_service ，也是报错如上。

3、具体我需要配置的参数如下：
turms:
  plugin:
    antispam:
      enabled: true
      dictParsing:
        textFilePath: /turms_ubuntu/turms/csv_files/in_use.csv
        textFileCharset: UTF-8
        skipInvalidCharacter: true

4、请问当前服务抽层到 turms-server-common 服务后，idea 的自动加载配置，又需要怎么解决？作者有考虑么？按照官网的设置，不生效的，应为turms-server-common服务迁走了。

**Comment by JamesChenX** [comment]
> 我把敏感词汇的配置放在 turms-plugin-antispam 的 resources 目录application.yaml下，服务启动turms_service ，报错:

The error logs mean the properties you specified don't exist. We design turms servers to throw when encountering unknown properties so that users can know they have configured the wrong properties.

It is correct that you configure turms-anti-spam properties under turms-service (because turms-anti-spam is a plugin for turms-service).

**But the properties name you configured is wrong. The correct naming style is shown in the following image:**

![image](https://github.com/turms-im/turms/assets/44962329/c9fdff95-fac5-4b42-afcd-738ec7fe25e7)

I checked the doc I wrote for `turms-plugin-antispam`, and I think you may followed the doc that uses the wrong naming style for properties. hhh.
I will correct the doc later.

> 请问当前服务抽层到 turms-server-common 服务后，idea 的自动加载配置，又需要怎么解决？作者有考虑么？按照官网的设置，不生效的，应为turms-server-common服务迁走了。

It seems you think `turms-server-common` is a service (i.e. a server), but it isn't.
`turms-server-common` is not a service, not an application, but is a library that is shared and used by turms servers (e.g. turms-gateway, turms-service, turms-ai-serving, and future servers), so `turms-server-common` itself cannot run.

**Comment by zhaieryuan** [comment]
Thank you very much for your reply.

---- Replied Message ----
| From | ***@***.***> |
| Date | 03/03/2024 11:39 |
| To | turms-im/turms ***@***.***> |
| Cc | zhaieryuan ***@***.***>,
Author ***@***.***> |
| Subject | Re: [turms-im/turms] how to config plugin config Properties in yml ， please for example ! (Issue #1407) |

我把敏感词汇的配置放在 turms-plugin-antispam 的 resources 目录application.yaml下，服务启动turms_service ，报错:

The error logs mean the properties you specified don't exist. We design turms servers to throw when encountering unknown properties so that users can know they have configured the wrong properties.

It is correct that you configure turms-anti-spam properties under turms-service (because turms-anti-spam is a plugin for turms-service).

But the properties name you configured is wrong. The correct naming style is shown in the following image:

image.png (view on web)

I checked the doc I wrote for turms-plugin-antispam, and I think you may followed the doc that uses the wrong naming style for properties. hhh.
I will correct the doc later.

请问当前服务抽层到 turms-server-common 服务后，idea 的自动加载配置，又需要怎么解决？作者有考虑么？按照官网的设置，不生效的，应为turms-server-common服务迁走了。

It seems you think turms-server-common is a service (i.e. a server), but it isn't.
turms-server-common is not a service, not an application, but is a library that is shared and used by turms servers (e.g. turms-gateway, turms-service, turms-ai-serving, and future servers), so turms-server-common itself cannot run.
