### ISSUE TITLE
The Message records byte[] messy code Error decode！

### ISSUE THREAD

**Issue by zhaieryuan** [turms-im/turms#1416]
我这边在message 消息中存储了二进制的json文本，当我去前台 queryMessage的时候，获取records 二进制数据进行，前端适配转换，出现了乱码，使用官网的develop分支进行的测试。而且这个问题是偶现的，怀疑是处理 rpc service中哪里使用了buffer 导致
![image](https://github.com/turms-im/turms/assets/127175435/1b151854-0814-4d46-b714-aab99e54144b)

客户端调用代码：
clientUserTwo.messageService.queryMessages({
                ids: [3116933066495946752],
                areGroupMessages: false,
                areSystemMessages: false
            }).then(res =>{
                console.log("****************************************************************************");
                // console.log(res);

                console.log(res.data[0].records);

                console.log(new TextDecoder().decode(res.data[0].records[0]));

                console.log(res.data[0].records[0].length);

            })

message 格式如下：

{
	"isGroupMessage": false,
	"isSystemMessage": false,
	"text": "message00000001",
	"recordBizStr": [
		"{\"type\":1,\"description\":{\"url\":\"[https://www.baidu.cn/tmp/im/1dc47ac1f206edd66ef89446761d8f82.jpeg\](https://www.baidu.cn/tmp/im/1dc47ac1f206edd66ef89446761d8f82.jpeg/)",\"size\":47719,\"mimeType\":\"image/jpeg\"}}"
	],
	"senderId": 10000,
	"senderName": "senderName_25d652a4664e",
	"targetId": 8453652352380108800
}

麻烦帮忙看下，感谢。

**Comment by JamesChenX** [comment]
It should not be the problem of the RPC service because if the RPC service encodes or decodes client messages incorrectly, turms clients will not have the chance to receive the responses and notifications.

I added some system tests about sending and receiving message records on my local computer, and all tests passed.
I also go through the workflow of sending and receiving message records from clients to servers and servers to clients, and they should work fine.

So I cannot reproduce the problems.

---

If you still encounter the problem, you can debug your clients and Turms servers yourself (that's why Turms is open-source).
After you find a message record is wrong. You can query the message document in MongoDB to check if the message document is stored incorrectly.
If the message record is stored incorrectly, you can debug the encoding and storing processing.
If not, you can debug the decoding processing to find out which step is wrong.
The debugging process should not be hard because you can reproduce the problem on your local, and you have all the source code and data in MongoDB.

**Comment by zhaieryuan** [comment]
1、我这边本地环境
windows、mongodb 7.05、使用git仓库develop分支最新代码

2、本地复现，前几次请求同一个消息转码出来的二进制是正确的，如上截图标注了，连续的快速点击按钮十几次后，同一个消息的records部分就会出现乱码。这里再附上一张本地在调试的代码。

![C83AB880-E66D-43e2-8849-C812910B6C0B](https://github.com/turms-im/turms/assets/127175435/4c7ae680-4076-491b-aa0d-73282e0172f6)



![image](https://github.com/turms-im/turms/assets/127175435/25bd8287-7eb6-47aa-9055-1d5f86adb292)

**Comment by zhaieryuan** [comment]
1、我这里通过排除法，最终锁定注释掉如下代码，records 里面的内容恢复正常
如图：
![image](https://github.com/turms-im/turms/assets/127175435/5d505fd2-c81a-47e4-b9af-004bf767a0b6)


2、当我将im.turms.server.common.infra.proto.ProtoEncoder#getDirectByteBuffer重写之后

![image](https://github.com/turms-im/turms/assets/127175435/c1bcdf2a-8be8-42cd-869f-060c16468c00)

输出明文的控制台信息发现：此处在records中加入了日志，信息。

![image-20240318113901388](https://github.com/turms-im/turms/assets/127175435/61ddad58-9b4a-43bd-989a-b8117d0a24f7)


![image](https://github.com/turms-im/turms/assets/127175435/daaa99ed-fd96-4e76-bd99-f759ec37076c)

3、以上是问题的实际情况反馈，感觉这个bug问题还挺严重的，希望作者能够尽快修复一下，不胜感谢。

**Comment by zhaieryuan** [comment]
这里注释掉图一代码, 并添加图二方法，即解决了问题，请作者参考一下，并解释一下原因最好，感谢。

![image](https://github.com/turms-im/turms/assets/127175435/f5cb5d92-2c61-4dd0-877e-7b3c03fd5f94)


![image](https://github.com/turms-im/turms/assets/127175435/a912cec0-555b-4194-a0ef-c263ff634e23)


![image](https://github.com/turms-im/turms/assets/127175435/712f1b30-5eb2-4cbe-91de-5eac13d0e231)

**Comment by JamesChenX** [comment]
Thanks for reporting and helping to pinpoint the bug.
I know now why it happens and will publish a bug fix and new release tomorrow or the day after tomorrow.

**Comment by JamesChenX** [comment]
@zhaieryuan The bug has been fixed.
You can pull the latest code on the `develop` or `master` branch or pull the latest docker image to have a try.

The root cause is the bytes parameters of turms requests may be recycled while the server handler is handling the request. For details, please check the commit: https://github.com/turms-im/turms/commit/296afaeb03e7b061619816c058a23cdc82855c06

**Comment by zhanchen18** [comment]
我的代码已经是这个版本了[https://github.com/turms-im/turms/commit/c8fe185037a3b96250038c78567b8e2094d4af2d](https://github.com/turms-im/turms/commit/c8fe185037a3b96250038c78567b8e2094d4af2d) 现在依然会有这个问题
