### ISSUE TITLE
Some question about data storage Need help

### ISSUE THREAD

**Issue by FantaZZ** [turms-im/turms#1456]
I saw that if the ```sequenceId``` of the message is turned on, it is automatically incremented in Redis.
Does this mean that Redis must be persisted instead of just using Redis as a temporary cache?

I also saw that ```ShardingAlgorithm``` is sharding based on user ID. If my Redis is a single node in the early stage and a cluster is built later, do I need to design a migration strategy?  Or I can only use the master-slave mode, always exposing only one node to Turms?

I'm not very familiar with Mongo. I found that the Mongo cluster has been configured in the docker file. Does this mean that if I need to expand the Mongo cluster later, I don't need to pay attention to the business logic like Redis and just operate the Mongo cluster directly?

**Comment by JamesChenX** [comment]
These are good questions, and I will write a detailed doc for them later (not that quickly as I am busy).

> Does this mean that Redis must be persisted instead of just using Redis as a temporary cache?

Yes. Turms servers need Redis to persist data, e.g. share the information of online sessions in the cluster.
You can uncomment the following lines to support data persistence in `docker-compose.standalone.yml`:
```yaml
#    volumes:
#      - "./redis/data:/data"
```
Note that Turms servers are design to try to recover from any disaster, which means even if Redis servers crash and lose all data, Turms servers will try to register all online sessions into Redis again.

> I also saw that ShardingAlgorithm is sharding based on user ID.

The `ShardingAlgorithm` is mainly designed for Turms to work with multiple Redis clusters (Yes, I mean Redis clusters, not Redis instances), so you don't need to consider it until one robust Redis cluster is not enough for your use cases.

> If my Redis is a single node in the early stage and a cluster is built later, do I need to design a migration strategy?

Redis has its own migration strategy, and Turms isn't special and has nothing to do with it.
So you can search something like `Redis migrate from one instance to cluster` on the Internet, and they should work for Turms too as Turms servers are not special.

btw, if you use Redis server from cloud providers, they should provide related migration guide for users. If not, you need to consider whether these cloud providers are professional and worthy to try.

> Or I can only use the master-slave mode, always exposing only one node to Turms?

Yes. Turms are designed for extreme cases, and that's why Turms servers support working with multiple Redis clusters, but it's recommended to use only one Redis instance, or one Redis cluster (you can configure Turms servers to work with the master node) at first.

> Does this mean that if I need to expand the Mongo cluster later, I don't need to pay attention to the business logic like Redis and just operate the Mongo cluster directly?

Turms is not special, and when you scale MongoDB cluster, you need to do **nothing** with Turms servers and Redis servers.

btw, scaling MongoDB cluster is quite easy, and you just input one command in fact, e.g.: `sh.addShard("rs1/mongodb0.example.net:27018")`. That's also why I like to cooperate with MongoDB because of their professional skills.

Reference: [Add Shards to a Cluster](https://www.mongodb.com/docs/manual/tutorial/add-shards-to-shard-cluster/)

**Comment by FantaZZ** [comment]
Thanks for your answer.
