### ISSUE TITLE
镜像启动后报错，导致minio初始化失败

### ISSUE THREAD

**Issue by water2060** [turms-im/turms#1459]
[20240511_0.log](https://github.com/turms-im/turms/files/15282068/20240511_0.log)

**Comment by JamesChenX** [comment]
The log `caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:27017` indicates that the Turms servers failed to connect to the MongoDB at `localhost/[0:0:0:0:0:0:0:1]:27017`, you need to ensure you start MongoDB at the correct host and port, and configure Turms with the corresponding MongoDB address.
