### ISSUE TITLE
压测

### ISSUE THREAD

**Issue by water2060** [turms-im/turms#1480]
希望官方提供一种压测的方法，比如用selenium。主要是想知道我部署的服务，在当前环境下可以承载多少在线用户同时发消息。或者目前有什么可用的方案吗？

**Comment by JamesChenX** [comment]
`selenium` is useless for Turms to perform load tests. Though developing a load testing system for Turms is easy (https://github.com/turms-im/turms/issues/606), I have no plan to develop it in the near future because there are tons of high-priority projects/features/enhancements needing to be done. FYR, I MAY start developing the system in 2026/2027.

> 或者目前有什么可用的方案吗？

No. You can write load tests that only work for your use cases, which should be easy. e.g. Fake data you need into the database, and create a lot of Turms clients to communicate with Turms servers, and monitor the metrics of Turms servers.
