### ISSUE TITLE
方案选择的思考

### ISSUE THREAD

**Issue by water2060** [turms-im/turms#1481]
1.我大体了解了一下turms-im项目的源码，我发现turms-im好像没有用xmpp协议，只是使用了protobuf。想知道作者是如可考虑设计的，做im，我看国外xmpp用的比较多。
2.turms-im对用户消息的安全保密有具体的设计吗

**Comment by JamesChenX** [comment]
> 我发现turms-im好像没有用xmpp协议，只是使用了protobuf。想知道作者是如可考虑设计的，做im，我看国外xmpp用的比较多。

For details, [About XMPP](https://turms-im.github.io/docs/server/module/xmpp.html#xmpp ), [关于XMPP](https://turms-im.github.io/docs/zh-CN/server/module/xmpp.html#xmpp).
In short, XMPP is useless if you want to implement efficient and flexible private IM applications, is only useful if you want to use public XMPP clients/servers out of the box, or you want your IM application to communicate with other IM applications by using the same XMPP protocol.

> 我看国外xmpp用的比较多。

Most of them use XMPP because of historical reasons. Some people think that XMPP has died away and has failed its job because there are almost no modern IM applications that will try to implement it.

From my perspective, if anyone wants to be a professional developer in the IM domain, it's recommended to learn XMPP (e.g. how it designs IM business components, e.g. message encryption, request/response schema; Why it is considered legacy, etc.), but it's highly not recommended to implement XMPP for any new modern IM applications unless you are very clear what you are doing.

> turms-im对用户消息的安全保密有具体的设计吗

No. Message encryption is illegal in China, so I have no motivation to support it.
And there are IM applications famous for message encryption.
