### ISSUE TITLE
Message Reaction

### ISSUE THREAD

**Issue by lovemianhuatang** [turms-im/turms#1491]
作者你好，请问Message Reaction是在开发中吗？进度如何？

**Comment by JamesChenX** [comment]
The feature is easy to develop but I am busy with tons of things, the feature may be delivered in 2024/08~09.

**Comment by lovemianhuatang** [comment]
能请教下思路吗？
1. 如何存储Message Reaction结构，新建一个集合吗？
2. 用户在线时能通过通知来接收某条消息的reactions，如果用户离线时产生的reactions变化临时存在redis中?上线后查询消费。这些离线时的reactions不能永久储存吧，有什么其他思路吗？

**Comment by JamesChenX** [comment]
Using shared `persistent notifications` (https://github.com/turms-im/turms/issues/1144) should be a good solution. For details:

1. (fan out write) Consider message reactions as notifications and use `persistent notifications`, which will store many kinds of notifications in MongoDB. Users can find the latest notifications by specifying a custom date range.
When turms-service receives a `message reaction update request`, it can update the message record first and then store message reactions as notifications in MongoDB and send it to message recipients.
This solution is easy for users to understand and use correctly, but it introduces fan out write, which is terrible in scalability.

2. (fan out read) Use a system message to indicate a message has been updated (e.g. recalled), but there is a problem for some use cases: If a client (designed and developed by Turms users, not by Turms) supports viewing/finding messages from the middle without the need of finding the latest messages (including system messages), the client may not know there is a message update happens. So the solution is okay, but not perfect because it cannot work well for all use cases.

3. (adopted, fan out read) Based on the first solution, and introducing a new concept `visibility` to `persistent notifications`, `visibility` can be used to control who can find the notifications, so:
  1. It can just store 1 notification but share it with many users, and there is no fan out write, which will be friendly in scalability.
  2. Some notifications can be collapsed into 1 notification for better performance.
  3. It can not only support message recalled/updated notifications but also other kinds of notifications (but we may not support other notifications until we find real requirements for them).
btw, the solution will also be used as the new default implementation of `message recall`, the previous implementation may be kept as it is easier for users to use if their use cases are simple.
