### ISSUE TITLE
关于如何发送自定义的通知内容

### ISSUE THREAD

**Issue by lovemianhuatang** [turms-im/turms#1504]
你好，我想请教一个问题，关于如何发送通知内容。

在响应客户端的查询时，比如QUERY_USER_PROFILES_REQUEST，是设置RequestHandlerResult.response直接响应当前用户的查询;
如果我想通知自己其他端在线客户端和相关用户时，比如UPDATE_USER_REQUEST，是设置RequestHandlerResult.notifications;
Notification只能设置TurmsRequest类型作为内容；

我如何返回自定义的内容？
比如在UPDATE_USER_REQUEST中，我想将用户完整的UserInfo当做通知内容发送给recipients？

<img width="862" alt="image" src="https://github.com/turms-im/turms/assets/41498415/9e86d0ea-28b4-4ce0-9109-1d926e34802e">

**Comment by JamesChenX** [comment]
> Notification只能设置TurmsRequest类型作为内容

Yes, `Notification` is designed to accept `TurmsRequest` only because all notifications are triggered by an `action`. In Turms, `TurmsRequest` can be considered the `action` implicitly.

> 如何返回自定义的内容？

There is no official way to pass custom data to notification recipients because we suggest the client application developers let the clients accept the notifications, and perform custom business logic and CRUD data based on the notifications **if they don't have a plan to modify the source code of Turms servers**. The solution is quite flexible and adaptive.

But if you are sure that you want to modify the logic and the source code of Turms servers for your business, I can add a new protobuf field (e.g., `repeated bytes extra_attributes`) in `TurmsNotification` so that you can use it to pass any custom data.

If you need it, please comment so I can give a support plan to you.

**Comment by lovemianhuatang** [comment]
谢谢，不用了，我使用了turms来二次开发，其他地方改动的比较多，这里我自己加了一个TurmsNotification中加了一个，和Data类似。
<img width="650" alt="image" src="https://github.com/turms-im/turms/assets/41498415/40bd51f2-2bcd-4a38-8b84-ceb20b23289e">

**Comment by zhanchen18** [comment]
@JamesChenX  I plan to add a new protobuf field ( repeated bytes extra_attributes) in TurmsNotification,But I don't know how to use this extra_attributes when creating notify. Can you help me

**Comment by JamesChenX** [comment]
@zhanchen18 Use the `repeated Value custom_attributes = 15` field in proto models, which should be what you want.
For details, [Request and Response Model](https://turms-im.github.io/docs/server/development/customization.html#request-and-response-model)
