### ISSUE TITLE
请教几个设计方面的问题

### ISSUE THREAD

**Issue by lovemianhuatang** [turms-im/turms#1508]
你好请教几个设计方面的问题：

1. 如何实现会话列表？类似微信
   显示会话的基本的信息（名称，头像），最新一条消息，未读消息数。
   未读消息数如何多端同步？
   收到单聊或群聊消息时，未读消息数服务端需要+1吗？还是只有客户端+1？
   
2. 在没有离线消息只有历史消息的设计下，同账号不同端在上线时如何获取自己离线期间接收到的消息？

**Comment by lucky-lbc** [comment]
> 你好请教几个设计方面的问题：
> 
>     1. 如何实现会话列表？类似微信
>        显示会话的基本的信息（名称，头像），最新一条消息，未读消息数。
>        未读消息数如何多端同步？
>        收到单聊或群聊消息时，未读消息数服务端需要+1吗？还是只有客户端+1？
> 
>     2. 在没有离线消息只有历史消息的设计下，同账号不同端在上线时如何获取自己离线期间接收到的消息？

你的会话列表解决了吗？  我有一个问题，如果是3000人大群，群成员的会话如何更新？

**Comment by JamesChenX** [comment]
> 你好请教几个设计方面的问题：
> 
> 1. 如何实现会话列表？类似微信
>    显示会话的基本的信息（名称，头像），最新一条消息，未读消息数。
>    未读消息数如何多端同步？
>    收到单聊或群聊消息时，未读消息数服务端需要+1吗？还是只有客户端+1？
> 2. 在没有离线消息只有历史消息的设计下，同账号不同端在上线时如何获取自己离线期间接收到的消息？

**The answer is `it depends on`. Think this way: `Think about how you want your IM application to be, rather than how Turms should be used`.**

When Turms features are designed, we collect user cases as many as possible, and then design Turms features to work efficiently with these use cases, and that's why Turms provides hundreds of properties to change its behavior.

**So we always try not to tell users how to implement their business sometimes because once we tell them, most users who read the message will think that's how Turms should be used, limiting users' imagination.**

If users just want to find the only answer, they should use [Rocket.Chat](https://github.com/RocketChat/Rocket.Chat) or something similar, so they don't need to think about how to design their own business.

---

I can give a brief workflow for you for reference now, but once you implement a real application, you will find there are many details you may not notice at first, it is just a workflow for reference, `Think about how you want your IM application to be, rather than how Turms should be used`.

> 显示会话的基本的信息（名称，头像）

1. Call `userService.queryRelationships` to find the relationships that you want.
2. Call `userService.queryUserProfiles` for detailed users' info, and display them on UI.
3. Call `queryUserProfilePicture` for the users' profile picture.

> 未读消息数如何多端同步？

Currently, unread message count is not shared across devices, the official implementation only supports independent unread message counts.
But the shared unread message count will supported soon in https://github.com/turms-im/turms/issues/575.

> 收到单聊或群聊消息时，未读消息数服务端需要+1吗？还是只有客户端+1？

As mentioned above, the official implementation only supports independent unread message counts currently, so it's efficient to let your client do this job to count the unread messages locally, and Turms servers don't even need to know this business feature.

> 在没有离线消息只有历史消息的设计下，同账号不同端在上线时如何获取自己离线期间接收到的消息？

Call `messageService.queryMessages` or `messageService.queryMessagesWithTotal` to get any messages that you want no matter these messages haven't been received or not.

e.g. call `messageService.queryMessages(deliveryDateStart: the delivery date of the last message stored on local - 5s)`

**Comment by JamesChenX** [comment]
> 你的会话列表解决了吗？ 我有一个问题，如果是3000人大群，群成员的会话如何更新？

Please open a new issue.
