### ISSUE TITLE
Add Security Policy for vulnerability reporting

### ISSUE THREAD

**Issue by Marcono1234** [turms-im/turms#1516]
Hello,
could you please add a [Security Policy file](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) to your GitHub repository, and ideally also [enable private vulnerability reporting](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository), so that users know how they can report potential vulnerabilities to you?

**Comment by JamesChenX** [comment]
Thanks for your suggestion!

We have added [the security policy file](https://github.com/turms-im/turms/blob/develop/SECURITY.md) and enable private vulnerability reporting.
Users can use the GitHub Security Advisory ["Report a Vulnerability"](https://github.com/turms-im/turms/security/advisories/new) tab to report vulnerabilities.

**Comment by Marcono1234** [comment]
Thanks a lot for this quick response and the well written security policy!
This resolved my original request here, so I will close this issue.

**Comment by JamesChenX** [comment]
I found that I cannot comment after publishing the advisor (https://github.com/turms-im/turms/security/advisories/GHSA-g9v7-9h57-3cmm) to the public. So I add a comment on it here.

---

Thanks for your reporting and detailed explanation!
I considered this a security enhancement since a hacker can only crack the password if they find the exact password or repeat the password.
I have fixed the problem (https://github.com/turms-im/turms/commit/8a13cfc63b0bdfc0aac6eaed5174e82e25bf1707), committed it on all branches, and published new images for servers.

Again, thanks for reporting!

**Comment by Marcono1234** [comment]
> I found that I cannot comment after publishing the advisor

Yes, that is quite weird. I have created https://github.com/orgs/community/discussions/133153 to suggest removing that limitation.

Is the version information of the advisory correct? Currently it says 0.10.0 is both affected and patched. Should the affected version rather be "< 0.10.0"? (I am not familiar with the versioning of this project though.)

Thanks for fixing this issue! Were you able to fix it in a backward compatible way, or was backward compatibility not a concern here?

Also, I have added one small suggestion here, I hope it is useful: https://github.com/turms-im/turms/commit/8a13cfc63b0bdfc0aac6eaed5174e82e25bf1707#r144719830

**Comment by JamesChenX** [comment]
> Is the version information of the advisory correct?

Yes. In fact, Turms only has one version `the latest version` currently because:
1. We have limited resources and no effort to maintain multiple versions.
2. It is recommended for users to always keep up with the latest version as the latest version contains more bug fixes, enhancements, and features.

> Were you able to fix it in a backward compatible way, or was backward compatibility not a concern here?

The fix is backward compatible since we use `versioning` in the BCrypt implementation. For new passwords, it uses the more secure version, and for old passwords, it uses the old algorithm, so it can work for both old and new passwords without users' intervention.
