### ISSUE TITLE
What are its features

### ISSUE THREAD

**Issue by ugintl** [turms-im/turms#208]
What are its features?

Is it in english?

**Comment by JamesChenX** [comment]
All documentation will be translated into English by the end of March and English will be the main language of this project. (I am busy with the three clients of turms presently).

In a word, compared with other instant messaging solutions on GitHub, you can use turms to build a new one of most of them just by creating your own configuration and plugins for turms.

**Turms is more like a technology foundation**. Taking ElasticSearch as an example. ElasticSearch is a search engine that can serve most of scenarioes about search no matter what kind of scenario it is, but you won't just put it in front of your users and may provide a beautiful seachbar backed by ES on your website that users can interact with. Turms is just like the engine that you can build a instant messaging app that is suitable for your users on it.

**Turms** is very flexible and powerful instant messaing solution that you can deploy 10 turms servers by just clicking your mouse
and they are auto-balancing without any help of other load balance servers (of course, they can still be integrated into turms cluster) and **turms-client-js/java/swift** will know how to talk with other users that connected with other servers and you can monitor turms servers on **turms-apm** and also view the statistics and users' data with beautiful UI on **turms-admin** for your PM/admins.
Customize turms without changing its source code just by your config and plugins for turms. (For further details, please access https://turms-im.github.io/turms/intro/features.html . it's Chinese but you can translate it into English by Google translate. I have no time for it for now)

Honestly, some drawbacks I need to point out:
1. Turms has not provide any UI framework for clients and also no plan for it because turms is designed to serve all kinds of scenarioes.
BTW: I know lots of newbies love UI but turms is not designed to collect "stars/forks" on GitHub.
2. The exposed APIs of Turms is not that steady as other solutions on Github, some params may change (but most of them are steady).
3. Turms doesn't have a solution for voice/video conference, file sharing and etc. Just keep remember, turms is just an engine that 
4. The status of Turms is between alpha and beta. So it's good to research but not good for you if you are rush 

BTW: As it declares, _The ultimate Free Open Source Solution for team communications_, [Rocket.Chat](https://github.com/RocketChat/) is, in my opinion, the most outstanding and wonderful instant messaing project on GitHub. If you just want to build an app without customizing too many things for your team or few users, you can try it.
