### ISSUE TITLE
turms-v0.9.0-SNAPSHOT.20200406 can not run, ClassNotFound

### ISSUE THREAD

**Issue by forxfoo** [turms-im/turms#392]
> envement:
> centos7
> jdk11
> turms-v0.9.0-SNAPSHOT.20200406

```
[root@HK1003-B4 bin]# sh turms.sh
+ exec /usr/java/jdk-11.0.7/bin/java -Xms1g -Xmx1g -Dio.netty.allocator.type=unpooled -XX:MaxDirectMemorySize=536870912 -Dspring.config.location=/root/turms-v0.9.0/config/application.yaml -cp '/root/turms-v0.9.0/lib/*' im.turms.turms.TurmsApplication
Error: Could not find or load main class im.turms.turms.TurmsApplication
Caused by: java.lang.ClassNotFoundException: im.turms.turms.TurmsApplication
```

please help me ~~ !!, thanks everybody.

**Comment by JamesChenX** [comment]
Short answer: you may need to add a parameter "-f"(means running turms as a fat jar). So try 
`sh turms.sh -f`
It's because turms itself can run as a fat jar or a thin jar and the snapshot file provides the fat jar of turms while "turms.sh" run as a thin jar by default.

BTW:
1. You may see another error later (something like "hazelcast.config is not found" ). If so, you need to specify the correct path of "spring.hazelcast.config"
(BTW: Hazelcast will be removed in the next release because of the reasons mentioned in https://github.com/turms-im/turms/issues/370 if you are interested)
2. It's better to use pooled direct memory instead of unpooled direct memory or you may notice frequent memory churn.
