### ISSUE TITLE
hello~ Is the code complete? there are too many red dots in intellij

### ISSUE THREAD

**Issue by forxfoo** [turms-im/turms#422]
This is a great project.  I`m learning your code, but encountered some problems.

branch: develop

![Xnip2020-07-13_20-28-59](https://user-images.githubusercontent.com/43881263/87305139-94069d00-c548-11ea-8ce2-114a73ea822d.jpg)

**Comment by JamesChenX** [comment]
Hi @forxfoo, it seems that you haven't installed the Lombok plugin in your IDEA.
And the errors should disappear after you install it.

**Comment by fortunesusw** [comment]
thanks very much

**Comment by forxfoo** [comment]
thanks very much.

**Comment by forxfoo** [comment]
I think this is a version bug.
> the mehtod getErrorAttributes(request, boolean, boolean, boolean) in `springboog 2.3.0.RC1`
> api doc https://docs.spring.io/spring-boot/docs/2.3.0.RC1/api/

![Xnip2020-07-14_13-21-12](https://user-images.githubusercontent.com/43881263/87387447-513ed680-c5d5-11ea-886b-624dfc891234.jpg)
![Xnip2020-07-14_13-21-46](https://user-images.githubusercontent.com/43881263/87387465-5dc32f00-c5d5-11ea-90ec-95b12a60ec61.jpg)

**Comment by JamesChenX** [comment]
The code is outdated and as you may have noticed that the repo hasn't updated for about 2 months because I am preparing for a huge update (0.10.0).

And if you wanna build and run the turms server from the source code, you can update the code in your local repo, or wait for the huge update that will be published late this month.

**Comment by forxfoo** [comment]
i got it .  thanks a lot.
