### ISSUE TITLE
turms-client-js demo error: HTTP Authentication failed; no valid credentials available

### ISSUE THREAD

**Issue by yjz1004** [turms-im/turms#579]
I published the program in the remote server.Then i modified the ws address in the business js file and published the trrms-client-js demo folder in local machine .Finally, i used the local browser visit the file, but it can't connnet the remote address,the errors as follows:

> WebSocket connection to 'ws://47.xx.xx.xx:9510/' failed: HTTP Authentication failed; no valid credentials available

![error](https://user-images.githubusercontent.com/48308568/101711584-cce27800-3ace-11eb-9d3d-1a6b1f7144de.png)

When i published the demo in the same remote server,it worked fine.Can files only be published on same remote server?

**Comment by JamesChenX** [comment]
It seems a problem of CORS security but not in fact because turms-gateway itself accepts all clients from anywhere.

The error happened because your userId or password was incorrect, or the account doesn't exist at all.

It worked fine on the local server because you may run it on your IDE and it runs with the property `turms.gateway.session.enable-authentication: false` defined in `application.yaml`. So your demo site worked fine because the server doesn't require authentication.

It cannot work after you published it on the remote server because you may run it with the application.yaml in `dist` folder while it doesn't set `enable-authentication`(true by default) to false. As a result, you got the error

> HTTP Authentication failed; no valid credentials available

**Comment by JamesChenX** [comment]
BTW: I just polished the code of business.js to remove the duplicate code for clarity.

**Comment by yjz1004** [comment]
According to your suggestion, i checked the password and 'turms.gateway.session.enable-authentication' prop.But,it's still not working.
Could you provide a latest demo server address so i can confirm is my server wrong?The address in readme is can't connect.

**Comment by JamesChenX** [comment]
If you are sure that the `turms.gateway.session.enable-authentication` is already set to false in turms-gateway (instead of turms because they are two different servers),
**you can try to check whether the inbound port 9510 is disabled by your server.**

**Steps to check whether the inbound port 9510 is disabled**
1. Try to access the endpoint `http://your-server:9510/reasons/login-failure` in your browser and you should get a response with `400`.
2. If not so, it means that 1. turms-gateway is down. 2. The inbound port 9510 is disabled.
You can enable the inbound port `9510` and try to run the demo again.

FYI: 
![image](https://user-images.githubusercontent.com/44962329/102172238-5fba5280-3ed3-11eb-88fd-a87f37de3fab.png)

**Comment by yjz1004** [comment]
> If you are sure that the `turms.gateway.session.enable-authentication` is already set to false in turms-gateway (instead of turms because they are two different servers),
> **you can check whether the inbound port 9510 is disabled by your server.**
> 
> **Steps to check whether the inbound port 9510 is disabled**
> 
> 1. Try to access the endpoint `http://your-server:9510/reasons/login-failure` in your browser and you should get a response with `400`.
> 2. If not so, it means that 1. turms-gateway is down. 2. The inbound port 9510 is disabled.
>    You can enable the inbound port `9510` and try to run the demo again.
> 
> FYI:
> ![image](https://user-images.githubusercontent.com/44962329/102172238-5fba5280-3ed3-11eb-88fd-a87f37de3fab.png)
