### ISSUE TITLE
A question about turms online at the same time

### ISSUE THREAD

**Issue by zhangyc** [turms-im/turms#948]
Hello, I would like to ask, how did you calculate the number of online users of 100K~10M? If the cpu4 core memory is 16G, how many online users can it support?

Because I am doing the final summary of the research, but I did not find any relevant descriptions. If you have a test report, my summary report will be more convincing.

**Comment by JamesChenX** [comment]
This's a good question.

## Why there isn't a benchmark report and tool (You can just skip this part if you don't have time)
Let's talk about the background of the benchmark first so that you can know why:
A long time ago (in 2020), I planned to deliver a simple benchmark report for developers, but I just find it's meaningless to do so because: The architecture of Turms servers can change and the features of Turms can be enabled or disabled according to different use cases.
For example, we try to support turms servers without a database if developers only want to deploy a push notification server without persisting any data; And the key feature `Sequence ID` of messages can be disabled or enabled, which have a large impact on performance.
As you may notice, different use cases use requires totally different system resources.

So I don't want to just deliver a benchmark report, but drafted a plan that we write a benchmark tool or even platform for developers to do benchmark their own use cases themselves. But, a benchmark platform isn't easy work that can be done in 1 or 2 months. That's why there isn't a benchmark report and tool currently.

## Solution
You can still test turms servers in an easy way (meaning you can write your own benchmark tests in minutes):
Just run turms servers on your machines, run your own client code and send different requests from clients that fit in your own business, and do the statistics that you want:

Pseudocode of a really easy example:
```
const clientCount = 50000;
for (var i = 0; i < clientCount; i++) {
  final client = TurmsClient();
  await client.userService.login(Int64(i), password: '123');
  final msgId = await client.messageService
      .sendMessage(false, Int64(i + 10), text: 'Hello Turms', burnAfter: 30);
  doStatistics();
  sleep(10millis);
}
```

For `100K~10M`, it doesn't mean a server should support 1M or more concurrent users and it's a terrible practice if someone really tries to do it. It means Turms project is designed for that case. If an application has only hundreds of concurrent users, they should try [Rocket.Chat](https://github.com/RocketChat/Rocket.Chat).
I wrote a simple test in 2020 for fun that runs 50K idle clients (it's isn't 100K because of the port limit in a machine) to connect to turms servers on a Linux machine with 32GB memory and 12 logic cores, and the server just works fine. But the test doesn't mean anything and is just for fun since it's too easy and that is why I don't write it on docs.

**If you need some benchmark test examples, I can write some examples recently.**
