### ISSUE TITLE
Why is netty channelInactive not being handled ?

### ISSUE THREAD

**Issue by nullnullruye** [turms-im/turms#970]
Hi, when I looked at your code, I found that the channelInactive event is not being handled. Here I have a question, the user's online status should be handled in channelActive and channelInactive.
After I checked the documentation, it is processed in the user's online status awareness. I found in the process of using netty that although the user is offline and calls channelInactive, the user's channel is still active and isWrite. What's the benefit of your design?

**Comment by JamesChenX** [comment]
Thanks for sharing your opinion.

> the user's online status should be handled in channelActive and channelInactive.

### Why a user's online status should not change in `channelActive`
A `client` **CANNOT** be recognized as any `user` in `channelActive` because it's just a TCP connection establishment, and that's why a `client` needs to set up a TCP connection first, and then sends a `CreateSessionRequest` in protobuf format to request `turms-gateway` to login as a `user`.
In other words, `Connection Establishment` and `User Login` are different things, just like different things on [OSI model](https://en.wikipedia.org/wiki/OSI_model)
That's why a user's online status should not change in `channelActive`.

For more details on how a client login as a user, you can check the docs: https://turms-im.github.io/docs/for-developers/architecture.html#%E5%AE%A2%E6%88%B7%E7%AB%AF%E8%AE%BF%E9%97%AE%E6%9C%8D%E5%8A%A1%E7%AB%AF%E6%A0%87%E5%87%86%E6%B5%81%E7%A8%8B

![image](https://user-images.githubusercontent.com/44962329/168466302-23b81cef-753f-4306-a75e-fa968f4ebc73.png)

---

### A user's online status should change (go offline)  in `channelInactive`
A `user` will be considered as `offline` when:
* Its TCP connection to `turms-gateway` is closed. We listen to the close event by the folowing code in the class `TcpServerFactory`:
`handle((in, out) -> connectionListener.onAdded((Connection) in, false, in.receive(), out, ((Connection) in).onDispose()))`.
And `onDispose()` is just the close event wrapped by `reactor-netty` and sent by `Netty`:
```java
default Mono<Void> onDispose() {
	return FutureMono.from(channel().closeFuture());
}
```
* The `user` sends a `DeleteSessionRequest` in protobuf format to `turms-gateway` though the TCP connection is **NOT** closed.
