### ISSUE TITLE
how to get history message list by turms-client-dart client ?

### ISSUE THREAD

**Issue by wtus** [turms-im/turms#976]
用中文了，英文太蹩脚了

1. deliveryDate 
~~client.messageService.send Message 方法 ，不传 deliveryDate 参数或者使用 DateTime.now() 会报错，把 deliveryDate 设置前一天就没问题，感觉是bug~~ 应该是服务器时间问题
`Unhandled Exception: 1410997394:1102:"deliveryDate" must be a date in the past or in the present`

2. 怎么获取两个用户聊天的历史列表，我尝试了 messageService.queryMessages 和 messageService.queryMessagesWithTotal 但是参数 ids 和  fromId 不太了解具体意义，只能获取到已登录client自己发的消息列表，应该怎么操作呢？

sugession:
用 client.dispose() 替代 client.close() 更符合 flutter 开发风格
```
  @override
  void dispose() {
    super.dispose();
    _refreshController.dispose();
    _turmsClient1.close();
    _turmsClient2.close();
  }
```

**Comment by wtus** [comment]
文档搜索功能好像用不了

**Comment by JamesChenX** [comment]
Thanks for your advice.

1. About `deliveryDate`:
Just as the log has said: `"deliveryDate" must be a date in the past or in the present`, meaning if the client passes a date after the server time, the client request will fail with the above error message.

**But I think it's better to not pass the `deliveryDate` by default on the client-side, meaning I will submit a PR as an enhancement recently.**

---

2. How to Get History Messages
Just pass parameters for  `messageService.queryMessages`.
I will write an article for it later and I am really busy currently.

4. How to get messages sent by oneself
By default, turms do NOT support the feature, but you can enable it by setting the property `turms.service.message.use-conversation-id=true`
For more design details: https://turms-im.github.io/docs/for-developers/schema.html#%E9%9B%86%E5%90%88%E8%AF%A6%E8%A7%A3

5. "ids" and "fromId"
"ids" means `Query Messages by the message IDs` and `fromId` means the recipient ID or the group ID and it depends on the 
For this, I will submit a PR to annotate method parameters on the client-side so that users can know their business meaning and usage as an enhancement. (Ticket: https://github.com/turms-im/turms/issues/977)

---

4. `dispose` or `close`
We choose the name `close` for the following reasons:
1. I believe a lot of non-native English speakers don't know the meaning of `dispose`, but they should know the meaning of `close` because `close` is a very easy word.
2. We try to use the consistent name `close` for different client implementations.
Exception: `ResponseError` of turms-client-js and `ResponseException` of turms-client-kotlin.
