### ISSUE TITLE
启动 turms-gateway，turms-service 项目报错

### ISSUE THREAD

**Issue by zhjphp** [turms-im/turms#985]
ERROR G hhipafgf                     main                  o.s.b.SpringApplication : Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'adminApiRateLimitingManager' defined in URL [jar:file:/mnt/d/home/project/turms/turms-gateway/dist/lib/app.jar!/BOOT-INF/classes!/im/turms/gateway/access/admin/throttle/AdminApiRateLimitingManager.class]: Bean instantiation via constructor failed; 
nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [im.turms.gateway.access.admin.throttle.AdminApiRateLimitingManager]: Constructor threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'node' defined in class path resource [im/turms/server/common/infra/cluster/ClusterConfig.class]: Bean instantiation via factory method failed; 
nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [im.turms.server.common.infra.cluster.node.Node]: Factory method 'node' threw exception; 
nested exception is java.lang.IllegalStateException: Failed to create the collection for the class: im.turms.server.common.infra.cluster.service.config.entity.property.SharedClusterProperties

因为涉及到二次开发项目，所以需要在开发环境中跑通。
启动turms-gateway，turms-service这两个服务，IDEA中启动，和再linux中使用run.sh启动，报错是一样的，都报这个错误。
目前找不到具体导致此错误的原因。

**Comment by JamesChenX** [comment]
I just tried to run `turms-service` and `turms-gateway`, and both works expectedly on Intellij IDEA (Windows) and Linux.
And it seems it failed to run because it cannot connect to MongoDB servers (I know that from my experience not from your log), so please ensure you configure the URI of MongoDB servers in `application.yaml` or as an environment variable `TURMS_GATEWAY_JVM_OPTS` for turms-gateway and `TURMS_SERVICE_JVM_OPTS` for turms-service. example in docker-`compose.standalone.yml`:

![image](https://user-images.githubusercontent.com/44962329/179204728-55f3f725-1f70-4dc2-adf2-a1e9c8a81569.png)
![image](https://user-images.githubusercontent.com/44962329/179204781-eac4d864-43b0-417e-b037-a063466e41bd.png)

**Comment by zhjphp** [comment]
> I just tried to run `turms-service` and `turms-gateway`, and both works expectedly on Intellij IDEA (Windows) and Linux. And it seems it failed to run because it cannot connect to MongoDB servers (I know that from my experience not from your log), so please ensure you configure the URI of MongoDB and Redis servers in `application.yaml` or as an environment variable `TURMS_GATEWAY_JVM_OPTS` for turms-gateway and `TURMS_SERVICE_JVM_OPTS` for turms-service correctly.
> 
> Take the example in `docker-compose.standalone.yml`:
> 
> ![image](https://user-images.githubusercontent.com/44962329/179204728-55f3f725-1f70-4dc2-adf2-a1e9c8a81569.png) ![image](https://user-images.githubusercontent.com/44962329/179204781-eac4d864-43b0-417e-b037-a063466e41bd.png)

thrank you,  it's works~
