### ISSUE TITLE
Running Spring Boot project directly failed. 

### ISSUE THREAD

**Issue by waitshang** [turms-im/turms#988]
I install redis, mongodb locally with binary archive (no pip, no docker). Starting redis, mongodb in default port. Then starting turms-server main method in dev profiles. And it comes out that: 
- "com.mongodb.MongoCommandException: Command failed with error 59 (CommandNotFound): 'no such command: 'enableSharding'' on server localhost:27017."

Log file:[turms-service_20220720_0.log](https://github.com/turms-im/turms/files/9147975/turms-service_20220720_0.log)

VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8

**Comment by JamesChenX** [comment]
It's a problem related to the config of MongoDB servers. Please ensure:
1. Running turms servers with MongoDB sharded clusters
2. Configuring turms servers to connect to the `mongos` server instead of the `mongo` server. For example:
(turms-gateway)
![image](https://user-images.githubusercontent.com/44962329/179972578-f1eb8619-ad59-49b6-b32a-59b4794a99e8.png)

(turms-service)
![image](https://user-images.githubusercontent.com/44962329/179972469-b4aa6417-71e2-4928-9415-563fe60b77b1.png)

And just try to run turms servers again.

**Comment by JamesChenX** [comment]
I notice that you have edited your post, and `no such command: 'enableSharding'' on server localhost:27017.` just means you connected to the wrong server, and you should connect to the **mongos** server.
