### ISSUE TITLE
How to query all related conversations for login user

### ISSUE THREAD

**Issue by weaponready** [turms-im/turms#995]
how to query all related  conversations (both private and group ones) for login user

**Comment by JamesChenX** [comment]
In turms, `conversations` consist of `conversations` and `messages`:
* conversations record the read date of private or group conversations
* messages just the user or system messages
---
On the client side,
1. To retrieve `conversations` in a simple (instead of a performant) way:
   * Retrieve the contacts by calling `user.queryRelationships(...)` for users and `group.queryJoinedGroupInfos(...)` for groups
   * Retrieve the conversations by calling `conversation.queryPrivateConversations(...)` for users and 
   * `conversation.queryGroupConversations(...)` for groups according to the data from the first step.
2. To retrieve `conversations` in a simple (instead of a performant) way, call `message.queryMessages(...)`

The above examples are just simple, and for more details, https://turms-im.github.io/docs/for-developers/status-aware.html#%E4%B8%9A%E5%8A%A1%E6%95%B0%E6%8D%AE%E5%8F%98%E5%8C%96%E6%84%9F%E7%9F%A5
